### ISSUE TITLE
Move cursor out of group tabs does not remove the hover state.

### ISSUE THREAD

**Issue by AlynxZhou** [aurelienpierreeng/ansel#106]
**Describe the bug/issue**

If I focus Technics tab, and move mouse to hove Sharpness tab, and move mouse cursor away, Sharpness tab is still in hover state.

![image](https://user-images.githubusercontent.com/8444615/222207682-d632a958-5e7e-4b18-8eb9-e51fdbd785d3.png)

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to 'darkroom'
2. Move cursor to a inactive group tab
3. Move cursor away

**Expected behavior**

It should not in hover state.

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : master
* OS                : 
* Linux - Distro    : Arch Linux
* Memory            : 32GB
* Graphics card     : NVIDIA RTX2070Super
* Graphics driver   : nvidia
* OpenCL installed  : yes
* OpenCL activated  : yes
* Xorg              : Wayland
* Desktop           : GNOME
* GTK+              : 3.24.36
* gcc               : 12.2.1
* cflags            : 
* CMAKE_BUILD_TYPE  : Release

**Comment by AlynxZhou** [comment]
It does not break any functionality, but I think it should not be like this...

**Comment by aurelienpierre** [comment]
You would think that using vanilla Gtk notebook would make things like that easier…

**Comment by aurelienpierre** [comment]
I don't reproduce.

**Comment by Jiyone** [comment]
I don't reproduce either.
(Ubuntu 20.04)

**Comment by AlynxZhou** [comment]
On my system it looks like this:

[Screencast from 2023-03-06 00-56-48.webm](https://user-images.githubusercontent.com/8444615/222974587-7c34394e-86a5-4b69-beb5-47987188e42a.webm)

**Comment by vithom** [comment]
Hello,
I can reproduce on my side although not quite as often as in this video.
I suppose something wrong with wayland because when I start the session with Xorg, the problem doesn't appears.
I'm also on arch.

**Comment by aurelienpierre** [comment]
In any case, given that the thing is a vanilla Gtk notebook, if there is a bug it's most likely on Gtk itself. My guess is the "mouse leave" event doesn't properly remove the hover state.

**Comment by AlynxZhou** [comment]
If not our problem, feel free to close this because it is harmless 😸️

**Comment by aurelienpierre** [comment]
Will doooo
