### ISSUE TITLE
February 28 version does not compile

### ISSUE THREAD

**Issue by koslowj** [aurelienpierreeng/ansel#107]
Atttempting to compile the February 28 version with gcc 12.2.1_p20230121-r1 under Gentoo Linux I get the following error:

/root/Ansel/src/common/imageio_rawspeed.cc: In function ‘dt_imageio_retval_t dt_imageio_open_rawspeed(dt_image_t*, const char*, dt_mipmap_buffer_t*)’:
/root/Ansel/src/common/imageio_rawspeed.cc:391:33: error: ‘class rawspeed::RawImageData’ has no member named ‘getByteDataAsUncroppedArray2DRef’; did you mean ‘getU16DataAsUncroppedArray2DRef’?
  391 |       memcpy(buf, (char *)(&(r->getByteDataAsUncroppedArray2DRef()(0, 0))), bufSize_mipmap);
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                 getU16DataAsUncroppedArray2DRef
compilation terminated due to -Wfatal-errors.

Making the suggested change (in 2 places) yields a further error

/root/Ansel/src/common/imageio_rawspeed.cc:493:41: error: ‘class rawspeed::RawImageData’ has no member named ‘getF32DataAsUncroppedArray2DRef’; did you mean ‘getU16DataAsUncroppedArray2DRef’?
  493 |         const Array2DRef<float> in = r->getF32DataAsUncroppedArray2DRef();
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                         getU16DataAsUncroppedArray2DRef
compilation terminated due to -Wfatal-errors.

which, after the suggested change, leads to

/root/Ansel/src/common/imageio_rawspeed.cc: In function ‘dt_imageio_retval_t dt_imageio_open_rawspeed_sraw(dt_image_t*, rawspeed::RawImage, dt_mipmap_buffer_t*)’:
/root/Ansel/src/common/imageio_rawspeed.cc:493:72: error: conversion from ‘Array2DRef<short unsigned int>’ to non-scalar type ‘Array2DRef<float>’ requested
  493 |         const Array2DRef<float> in = r->getU16DataAsUncroppedArray2DRef();
      |                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
compilation terminated due to -Wfatal-errors.
 
This is the first time I have trouble compiling Ansel. 

-- Jürgen

**Comment by l-28** [comment]
I don't understand any of the error log, but since it mentions rawspeed, I thought it could be related to the backported up-to-date Libraw and Rawspeed changes from darktable to Ansel. Maybe this helps also: https://github.com/aurelienpierreeng/ansel/commit/824b2d35bdcae0d3a226b226a096b1ae48246dc6 

In the matrix chat Aurélien advised to `git submodule update` before building referring to that backport on Sunday 26th.

**Comment by koslowj** [comment]
git submodule update --init before recompiling did the trick, thanks! The issue is closed.

-- If I don't see you no more on this world
Juergen Koslowski I'll meet you on the next one
***@***.******@***.***)and don't be late!
Sent from Swiss-based encrypted [ProtonMail](https://protonmail.com), (Jimi Hendrix, Voodoo Child, SR)

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
