### ISSUE TITLE
Display metadata module makes film strip disappear (darkroom)

### ISSUE THREAD

**Issue by pedrorrodriguez** [aurelienpierreeng/ansel#111]
**Describe the bug/issue**
Clicking on the display metadata module in the darkroom hides the film strip. It does not respond to the shortcut to show/hide it. The only way to bring it back is to resize the window.

EDIT: If you ctrl+scrollwheel and reduce its size to the minimum, then resize the window, the issue is gone. It has to do with the module's height. Once the module "runs out" of vertical space it pushes the filmstrip out of the screen.

EDIT 2: If you try in an unmaximized window, going from a very short to a very tall display metadata module (via ctrl+scroll) it actually resizes the window until it's pushed out of the screen, if that make sense. The film strip doesn't come back, because the window doesn't get resized after the module is collapsed. 

**To Reproduce**
Reproducible: always.

1. Click on the display metadata module.
2. The film strip disappears.
3. Resize window.
4. There it is again!

**Expected behavior**
Film strip remains unaffected by the display metadata module.

EDIT: display metadata shouldn't be able to resize the window. 

**Screenshots**
![display-metadata-crash2](https://user-images.githubusercontent.com/64545422/222471120-2340ffb9-5b2c-4775-988e-2b9e38097db8.png)

**Screencast**
If necessary I'll upload later tonight.

**Platform**

* darktable version : Ansel-0.0.0+146.gc80967879-x86_64.AppImage and Ansel-0.0.0+148.g192af7a87-x86_64.AppImage
* OS                : Linux 5.15.0-56-generic
* Linux - Distro    : Ubuntu 20.04.5 
* Memory            : 8gb
* Graphics card     : Intel Corporation HD Graphics 620 (rev 02)
* Graphics driver   : i915
* Xorg              : X.Org X Server 1.20.13
* Desktop           : KDE Plasma

**Comment by blonchkman** [comment]
I confirm the behavior (build 6a7d389):

1. the filmstrip disappears when the metadata module is opened
2. If, and only if, the scope module is displayed on the left. If the scope is on the right, the filmstrip panel behaves normally.

kindest regards
