### ISSUE TITLE
Translation: Consider only use English in code?

### ISSUE THREAD

**Issue by AlynxZhou** [aurelienpierreeng/ansel#112]
This is just a low priority suggestion, but I noticed we now have a menubar, and needs to switch views in menu, however, the menu label, "_Ateliers", google translate tells me that it is a French word 😸️

If we have po files for French, then we'd better only put English in code, maybe just `Views` is OK.

Or if you tell me that the word is also a English word, then just close this, English is not my native language so I may take some mistakes.

**Comment by aurelienpierre** [comment]
It's English too, borrowed from French with the same meaning (means workshop with a more artsy connotation).
