### ISSUE TITLE
 Very Different Initial Rendering of some Nikon NEF RAW File

### ISSUE THREAD

**Issue by dnlyko** [aurelienpierreeng/ansel#113]
I just wanted to bring this to your attention.
Was using DarkTable and decided to use Ansel instead.
I posted this issue on PIXLS.US...
[https://discuss.pixls.us/t/very-different-initial-rendering-of-raw-file-possible-corrupt-file-but-renders-ok-in-rt/35297](url)
and this is the proposed solution...
[https://github.com/darktable-org/rawspeed/commit/68b328da1ee9ec69eaddfd28022b0541561e94d0](url)
![lighttable](https://user-images.githubusercontent.com/38403574/222871763-201ff783-a748-42e9-b417-69fbd2b2d38e.jpg)
![darktable](https://user-images.githubusercontent.com/38403574/222871781-1176dd97-8865-4b9a-bb98-201a8a31b48f.jpg)

**Comment by aurelienpierre** [comment]
Ansel uses the stable branch of Rawspeed, so when this commit makes it there, it will be available.

**Comment by aurelienpierre** [comment]
I had to make Ansel use Rawspeed dev branch, for other compatibility reasons. Is that fixed now ?

**Comment by pedrorrodriguez** [comment]
This seems like a wontfix if no further feedback is given

**Comment by dnlyko** [comment]
Has been fixed
