### ISSUE TITLE
A view mode of selected images for comparing side by side (two) images

### ISSUE THREAD

**Issue by mmoqui** [aurelienpierreeng/ansel#116]
In the lighttable, I used to choose the photos to put into a given serie or to an existing project (the editing process that is made up of several steps). It comes frequently I need to compare side by side two images in order to choose only one of them. When there are several similar images or images with a similar meaning, I do this pair to pair: I chose one of the two first images, then the chosen one with another one, and so on until there is only one image (I use the stars to select the images to keep for my series/projects: in each editing step, the images to keep have an additional star).

The issue here is the view mode (the culling mode) allowing me to perform this way of choosing one image among several selected ones has disappeared in Ansel.
It would be nice to have a view mode or a function for selected images similar to the the culling view in fixed mode (only a given number of images are rendered side by side; for me it is two) for a set of selected images.

**Comment by aurelienpierre** [comment]
Culling mode was 2500 lines of shitty code, broken in subtle ways and generally unmaintainable. Culling is planned to come back as a filter.

**Comment by mmoqui** [comment]
Ok, nice to have this functionality one day. What do you mean when you wrote "as a filter"? A filter like the ones on the stars or on the color flags?

**Comment by mmoqui** [comment]
Ha ok. Good idea.
Another question: once some images selected and the lighttable filtered to this selection, some of these images could they be selected again  for, for example, file operations or development operations (like it is with any filtered view)? Or, if an image isn't more selected whereas the filter is active, is this image will disappear from the filtered view?

**Comment by aurelienpierre** [comment]
I'm thinking about removing selected state after entering the restricted selection (culling mode), so all interactions will be consistent with default lighttable/filemanager view, and perhaps a right-click contextual menu that would allow to remove any image from the current view.

**Comment by mmoqui** [comment]
Ok, thanks for the answers.

**Comment by aurelienpierre** [comment]
Done : https://github.com/aurelienpierreeng/ansel/commit/2f267d6211dd9fb228b11795f356e9bf4914e585

You will find a "selected" button in the top menu of the lighttable that allows you to restrict the current view to selected files. It's a toggle button, so if you push it a second time, the view is restored as it was, including the the selection.
