### ISSUE TITLE
Add support for HEIC/HEIF

### ISSUE THREAD

**Issue by Deltafire** [aurelienpierreeng/ansel#117]
Most modern cameras are now offering this format.  Upstream has supported it since 2021:

https://github.com/darktable-org/darktable/pulls?q=heic

**Comment by Jiyone** [comment]
I've tried to make it work on Upstream too but I couldn't 🤷🏻‍♂️ 
the needed libraries are "not found" in the tests done before building the app even tough they are installed ...
(ubuntu 20.04)

**Comment by aurelienpierre** [comment]
Supported where the proper HEIF headers are on installed on your system. It's version-dependent.

**Comment by 0phoff** [comment]
Took me quite some time to figure out, but you specifically need to install version 1.13.0 of libheif. The newer 1.16 version does not seem to be working, even though compilation of Ansel works and cmake tells you libheif is detected and enabled.

```
# Quick installation guid for libheif 1.13
git clone git@github.com:strukturag/libheif.git
cd libheif
git checkout v1.13.0
./autogen.sh
./configure
make -j8 # adapt number of jobs depending on computer
```

**Comment by etrigan63** [comment]
So has this been implemented or not? The current build of `ansel` does not see HEIF files.
