### ISSUE TITLE
unhandled exception

### ISSUE THREAD

**Issue by dnlyko** [aurelienpierreeng/ansel#130]
## Description of the bug
![crash](https://user-images.githubusercontent.com/38403574/226060568-138f529f-9f36-43ab-be95-b45c4ff54a47.jpg)

[ansel_bt_K3A411.txt](https://github.com/aurelienpierreeng/ansel/files/11006664/ansel_bt_K3A411.txt)

**To Reproduce**

maximized view
open image in darkroom to edit
select color assessment
reduce view from maximized to window size
grab window at bottom right corner and drag up/left to reduce window size

## Expected behavior
see image

## Context

**Screenshots**

**Screencast**

## System

* darktable version : 0.0.0+276~gf6f910058
* OS                : windows 11
* Linux - Distro    : 
* Memory            :64gb
* Graphics card     :gtx1060
* Graphics driver   :
* OpenCL installed  :yes
* OpenCL activated  :yes
* Xorg              :
* Desktop           :
* GTK+              :
* gcc               :
* cflags            :
* CMAKE_BUILD_TYPE  :

**Additional context**

 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`) any image

 - Do you use lua scripts? no

**Comment by aurelienpierre** [comment]
Reproduced on Linux. Sounds like the pipeline size for the resized preview gets set to 0.

**Comment by aurelienpierre** [comment]
Should be fixed in 8fe94c2629b8536b202779581b867689b6514414, can you test ? (Prebuilt package will be available tonight)

**Comment by Scorpion078** [comment]
I reproduced it on Windows, installed the fix and it seems that solved it

**Comment by aurelienpierre** [comment]
Cool. One less.
