### ISSUE TITLE
Highlights reconstruction (guided laplacians): increase max number of iterations for smaller diameter sizes 

### ISSUE THREAD

**Issue by pedrorrodriguez** [aurelienpierreeng/ansel#133]
Often the best diameter size is rather small, with many iterations. When you max them out at 256, the transitions are very smooth, but the magenta highlights are not completely gone. Inpaint a flat color mitigates the issue a bit, but often doesn't completely fix the issue. Filmic's hl reconstruction helps if you don't mind bleaching them. 

Can the max number of iterations be allowed to be increased (manually via right click), so that we keep the smoothness, but get rid of magenta highlights and preserve color as much as possible?

**Comment by aurelienpierre** [comment]
yes
