### ISSUE TITLE
[UI] Library  module doesnt scale the list of locations

### ISSUE THREAD

**Issue by muenznej** [aurelienpierreeng/ansel#144]
Hello!
Firstly, thanks for the efforts making dt/ansel slim and maintainable. 

## Description of the bug

I think there is a bug in the UI. For me the list of locations does not scale to more than one item ( blue arrow ) and the module isnt expanding properly, imo. I couldn't find a setting to resolve this.
I have a similar scaling problem with "Recent Collections" as well ( there are only two items listed )
Please let me know if you need more details.

**To Reproduce**

1. open ansel "Library" module

## Expected behavior
I think the modules' menus should show more than 1 entry and scale properly with respect to a maximum module size. 

## Context

**Screenshots**
![Screenshot 2023-04-10 103836](https://user-images.githubusercontent.com/26899110/230868821-fff8bd47-c317-47b7-91f2-7494b977afa4.png)

## Which commit introduced the error

Since i tested ansel.  I use/used dt years before, never had such problems.

## System

* darktable version : ansel-0.0.0+283.g9405171cc-win64
* OS                :  windows 11

**Comment by l-28** [comment]
This should get you out of trouble:
https://ansel.photos/en/doc/modules/#module-resizing

But that doesn't explain why it happened in the first place...

**Comment by muenznej** [comment]
Wow, thank you very much for the quick solution!
I dont know why it was like this 🤷🏽  If noone else has this problem, then please ignore and thanks for pointing out that  ctrl+mousewheel is the solution.
