### ISSUE TITLE
No more apply development menu

### ISSUE THREAD

**Issue by beudbeud** [aurelienpierreeng/ansel#146]
## Description of the bug
The apply development menu disappear and i don't know if is a feature or a bug or i make it disappear.

**Screenshots**
[![04-13-2023-1681412342.jpg](https://i.postimg.cc/P5g0D43n/04-13-2023-1681412342.jpg)](https://postimg.cc/k2yj3xPT)

## Which commit introduced the error

i don't know

## System

* Ansel version :  build from master
* OS                : e.g. Linux - kernel  6.2.6-76060206-generic
* Linux - Distro    : e.g. Ubuntu 22.04
* Memory            : TX 2070 Super
* Graphics card     : Nvidia 
* Graphics driver   : 525.89.02
* OpenCL installed  : yes
* OpenCL activated  : yes
* Xorg              :  11.0
* Desktop           : i3wm
* GTK+              :
* gcc               :
* cflags            :
* CMAKE_BUILD_TYPE  : Release

**Additional context**

I build my own flapak version of Ansel
https://pastebin.com/shJiajeG

**Comment by l-28** [comment]
Hey @beudbeud, 

I think you will find, what you are looking for in the "Edit" menu at the top of the screen.

**Comment by beudbeud** [comment]
Thanks, i find it in menu Edit
