### ISSUE TITLE
Can't build last master branch with Release mode due to "may be uninitialized error"

### ISSUE THREAD

**Issue by dydyamotya** [aurelienpierreeng/ansel#148]
## Description of the bug

If one tries to build 664c527d3835cd53233c8caef991d5610f23a01b commit from master branch (last for now), one will catch an error due to uninitialized pointer in tagging.c.

**To Reproduce**

1. Try to build this commit by line: sh build.sh --build-type Debug --install --sudo --clean-all
2. Get an error.

## How to fix
On line 1796 in src/libs/tagging.c initialize this pointers by:

  GtkWidget *category = NULL;
  GtkWidget *private = NULL;

If you prefer pull request, I can do it a little bit later.

**Comment by aurelienpierre** [comment]
Fixed, thanks !
