### ISSUE TITLE
FR: Increase max brightness value of sliders inside color calibration's brightness tab (manual input only)

### ISSUE THREAD

**Issue by pedrorrodriguez** [aurelienpierreeng/ansel#154]
This would allow for increased contrast beyond what is currently possible. I think the current values are safe for the default, but I would like to be able to manually increase values beyond +1.

**Comment by aurelienpierre** [comment]
No, that's actually quite bad since brightness > 2 leads to division by 0 in the color model. Brightness should not be used for contrast. I'll actually do the opposite and reduce the available range for safety.
