### ISSUE TITLE
False color with color calibration

### ISSUE THREAD

**Issue by blueberry38** [aurelienpierreeng/ansel#156]
## Description of the bug 
Calibration not working, either on full image or using a spot in the image
![Capture d’écran 2023-05-28 211525](https://github.com/aurelienpierreeng/ansel/assets/2437405/058a9f09-a2f5-4132-95bf-c044be223a86)

* ansel version : 285
* OS                : win 11/linux ubuntu 22 wsl

**Comment by l-28** [comment]
Hey @blueberry38,

I think you will have to give a little bit more information to enable others to help you. Do you encounter this problem on all your images? What steps in Darkroom have you taken before you use "Color Calibration"? It might be most helpful to share your RAW and xmp so others can check whether they can reproduce your problem or find a setting in the pipeline that explains the behaviour.

**Comment by blueberry38** [comment]
> Hey @blueberry38,
> 
> you will have to give a little bit more information to enable others to help you.
> 
> Do you encounter this problem on all your images? What steps in Darkroom have you taken before you use "Color Calibration"? It might be most helpful to share your RAW and xmp so others can check whether they can reproduce your problem or find a setting in the pipeline that explains the behaviour.
> 
> Also you might find more people responding to your request at: https://community.ansel.photos/

Problem on all images. Steps: BW - exposition - calibration
Aurélien asks me to open a bug report
Thank's

**Comment by l-28** [comment]
I only just read the matrix chat concerning this issue, my bad - sorry for the noise.

**Comment by blueberry38** [comment]
No problem. Try to up to date Opencl driver but BSoD... So reinstall Win 11 and Ansel, all works well. Just Have to reinstall wsl an Ubuntu. Tank's for help .
