### ISSUE TITLE
Improve vertical scrolling step

### ISSUE THREAD

**Issue by aurelienpierre** [aurelienpierreeng/ansel#16]
As mentioned in #11, scrolling step is too small.

Solution 1: map the scrolling step to the equivalent height of, say, 5 text lines (fetching the actual font size with DPI factor/high-res scaling factor).

Solution 2: (only if the previous one fails) give up and make it user-defined (more prefs, yay \o/).

@StudioPetrikas & @pedrorrodriguez : what is your OS/desktop environment ? (Please don't say Mac OS).

**Comment by StudioPetrikas** [comment]
Worse - Windows.

Just in case: interestingly @pedrorrodriguez has reported that scrolling is too slow, while my report was that it was too fast (1 'tick' of the mouse wheel jumps exactly 4 sliders in 'colour balance rgb')

I think your spider senses might be right - this could be OS-dependent.

**Comment by aurelienpierre** [comment]
> Worse - Windows.

Better because I have a Win 10 workable instance and my wife will kill me anyway if dt doesn't work on Win. So…

**Comment by pedrorrodriguez** [comment]
I'm on Linux. Thanks for working on this

**Comment by aurelienpierre** [comment]
I found out that there are 2 different ways of scrolling with 2 different scrolling steps : one incremental scroll, linked to the mouse wheel ticks, and one smooth scrolling, linked to touchpad/trackpad scrolling. As you may imagine, the incremental scroll is pretty direct to deal with, but the smooth scrolling may vastly depend upon your OS motion sensitivity.

What kind are you both using ?

**Comment by StudioPetrikas** [comment]
98% mouse 2% touchpad here. If you changed how the touchpad behaves, I wouldn't notice it - not used to it at all.

I do envy the smooth-scrolling of the touchpad, as it's less jarring and disorienting; but I understand that the delay the smoothness would introduce would be annoying to power-users.

**Comment by pedrorrodriguez** [comment]
I'm almost the opposite. More like 90% touchpad, 10% mouse. It depends if I'm on the go/on the couch vs. at my desk.

**Comment by aurelienpierre** [comment]
So the gap might be too high for incremental and too low for smooth scroll.

**Comment by pedrorrodriguez** [comment]
Isn't this already fixed?
