### ISSUE TITLE
Provide Flatpak version of app

### ISSUE THREAD

**Issue by Grzanka99** [aurelienpierreeng/ansel#162]
**What is the current problem you are facing ?**
Instalation and using the app is very hard and inconsistent. Also open time is really long as it is appimage. Before I was using apx to use AUR build of app but it's borked since recent changes, so easier to maintain way as flatpak would be much better user experience

**Where in your workflow does your problem occur ?**
I often reopen app to review my edits and with appimage version I have to first open file manager, navigate to appimage file and only then I can open an app

**Additional context**
As the flatpak is future and easiest way of sharing software between linux distro, I think that Ansel would get much more attention if it was available in flathub or atleast easier to use/install as flatpak.

**Comment by ptilopteri** [comment]
why do you not make a link to the appimage darktable application and start it instead of using your file manager?

**Comment by Grzanka99** [comment]
> why do you not make a link to the appimage darktable application and start it instead of using your file manager?

My point is that there should be easy way to use the app for regular user, even tho I'm using linux exclusively for 2 years now (and 4 total) I have no idea how to make desktop entry (I assume that's what you meant) without googling.

**Comment by ptilopteri** [comment]
if you want a desktop entry, just copy another and substitute appropriate values.  I have one for openSUSE Tumbleweed:
   http://wahoo.no-ip.org/~paka/darktable

**Comment by Grzanka99** [comment]
> if you want a desktop entry, just copy another and substitute appropriate values. I have one for openSUSE Tumbleweed: http://wahoo.no-ip.org/~paka/darktable

I think you still not get my point. If I understood Ansel supposed to be simplified version of darktable, not hacky as darktable and easier to use for regular user. Currently, even updating the app - by going to github/ansel page and downloading binary - it's not the way to go, it's windows way.

I;m not asking for help to create desktop entry (tho thanks for the link, I will use it), I asking for easier way to download, update and run software.

I put this issue as "Feature", not as "Error", I just want to see this in future.

**Comment by l-28** [comment]
Hey @Grzanka99, 

this might interest you: https://community.ansel.photos/view-discussion/flathub

Aurélien states that he won't provide a flatpak version, because 

> Flatpak sucks. It needs to run a power-hungry service in background, needs to reinstall packages for graphic drivers (not sure if they are bindings or actual drivers), then it sandboxes software and config files in weird places : the whole thing is bloatware serving bloatware and only feeding the Snap vs. Flatpak church war.

**Comment by Grzanka99** [comment]
@lukadh Ok, I get the point, but is it really matter what user gonna run if he want's to run it this way? I'm open to help with porting (I could try my best :smile:  tho I have no experience with flatpaks and little with C) to flatpak version, in theory should not be that hard, and afterl all, going into github, check if there're some updates in code and then decide if download new appimage? I guess that's not good user experience... feels kinda hacky :smile:

**Comment by aurelienpierre** [comment]
You can link the AppImage package to your desktop menu using `.desktop` files or use AppImage launcher. See https://ansel.photos/en/doc/install/linux/#run-the-appimage. On KDE, it's even simpler: you can just open the AppImage and right-click on the task manager icon and select "pin to task manager".

Putting together the AppImage was 80h of work altogether, I don't have time to waste on Flatpak. Then people will as for a Snap package. This is nonsense.
