### ISSUE TITLE
librairy request error by timestamp with win10 or win11  

### ISSUE THREAD

**Issue by olliwa-git** [aurelienpierreeng/ansel#165]
## Description of the bug

The request by date creates the tree but looses the link with the photos to display

**To Reproduce**

be on windows 10 or 11 OS

1. Go to 'Lighttable/Library'
2. Click on 'Queries'
3. Scroll down to 'date taken'
4. See the tree just under, 
5. Double click on item of the tree 
6. See the message  "there are no images in this collection"

## Expected behavior
Like linux version, we should see the photos when clicking on item of the tree

## Context

**Screenshots**

![image](https://github.com/aurelienpierreeng/ansel/assets/75898406/645bfe66-778c-4e46-befa-f7bd5fcc37f7)

**Screencast**

## System

* ansel version : 0.0.0+298~g8107fa6cbc
* OS                :  Win11
* Linux - Distro    : 
* Memory            :
* Graphics card     : Intel
* Graphics driver   : Intel
* OpenCL installed  : yes
* OpenCL activated  : yes
* Xorg              :
* Desktop           :
* GTK+              :
* gcc               :
* cflags            :
* CMAKE_BUILD_TYPE  :

**Additional context**

**Comment by aurelienpierre** [comment]
Cause seems to be inconsistent timestamps on Windows

**Comment by andre-doherty** [comment]
hello, 
FYI i created a pull request yesterday that contains the fix for the timestamp issue we talked about a while ago.
This patch comes from the darktable code, and has been tested successfully on my local windows 10 OS. 

André
