### ISSUE TITLE
Ansel does not preserve/keep the current **instance** of a module opened/expanded when switching between image duplicates

### ISSUE THREAD

**Issue by barathrm** [aurelienpierreeng/ansel#166]
## Description of the bug

Ansel does not keep the currently opened **instance** darkroom module open/expand when switching between duplicate images, only the general type of the module.

**To Reproduce**

- Open an image in the darkroom view
- Create a duplicate of the image using the `Duplicate manager`
- Create a new instance of a module. I've had the issue with a new instance of `Color balance rgb` with a custom name.
- Open/expand this new instance of the module, make some adjustments (not sure if necessary to make adjustments)
- Note that your new instance of the module is open.
- Switch to the other duplicate of your image
- Note that the `Color balance rgb` module is switched to the **default** instance of the `Color balance rgb` module, **not** your custom instance.

## Expected behavior

When switching between image duplicates ansel should remember which instance of a module I had open, instead of only which type of module.

## Context

I often have a separate instance of the color balance rgb module just for contrast changes, or color grading etc. This bug has made me adjust contrast in the wrong instance of the module a few times when switching back and forth between modules.

## System

* darktable version : 0.0.0~git283.9405171c-10.30 from https://build.opensuse.org/package/show/home:fawz:ansel/ansel
* OS                :   linux
* Linux - Distro    : openSUSE tumblweed

Let me know if you need any more info.

**Comment by pedrorrodriguez** [comment]
When you create a duplicate, you basically do that, make a copy. They are not synchronized, though. If you create a duplicate, create a new instance of color balance RGB, adjust it, and go back to the original image, it is normal that it would go back to the first color balance RGB instance. Perhaps i misunderstood?

**Comment by barathrm** [comment]
> When you create a duplicate, you basically do that, make a copy. They are not synchronized, though. If you create a duplicate, create a new instance of color balance RGB, adjust it, and go back to the original image, it is normal that it would go back to the first color balance RGB instance. Perhaps i misunderstood?

So my workflow is this.

- open image
- create a custom instance of `color balance rgb` and call it "contrast", for example
- create a duplicate of the image, which now also contains an instance of `color balance rgb` called "contrast"

As a user, if I switch from one of these duplicates to the other, I'd expect ansel to keep me in the duplicate's equally-named `color balance rgb` module named "contrast", since it has the same name and was created as part of the duplication process, not after it.

As a developer I realize that, behind the scenes, they might be impleted as completely separate instances of a module. But I'd also assume that it's possible, when switching to another image/duplicate, to check whether there's a module with the same name (or a hidden behind-the-scenes ID) in the image-to-be-opened which matches the previous image's module, to be able to have this kind of editing continuity.

**Comment by pedrorrodriguez** [comment]
I see. Don't know how feasible it is. Let's wait for AP's take on this.

**Comment by aurelienpierre** [comment]
The collapsed state is remembered per module and is a property of the application (saved in anselrc), it is not remembered per instance and instances are a property of the current editing only.

The request here makes sense from an usability perspective, but I don't see a way to achieve it with the current modular approach, except storing the GUI state in database for each editing, which means adding a new table and bumping the data scheme version. But the database should store pipeline parameters and I'm reluctant to add GUI info in there.

The least bad option would be to store a text sidecar config file for each picture/duplicate with GUI properties.
