### ISSUE TITLE
Duplicate Manager fails to work

### ISSUE THREAD

**Issue by koslowj** [aurelienpierreeng/ansel#179]
After the latest update the duplicate manager only shows an preview of the currently selected image, but no buttons to duplicate it or to open the original unprocessed image.  I did a complete re-compile yesterday and today.  exiv2 is up-to-date (shouldn't be relevant).

**Screenshots**
file:///tmp/screenshot.jpg

## System

* ansel version : 26acfc2  , self-compiled from scratch
* OS                : linux-6.1.31-gentoo 
* Linux - Distro    : Gentoo
* Memory            : 16 GB
* Graphics card     : Nvidia GM204GL [Quadro M5000]
* Graphics driver   : 525.116.04-r2
* OpenCL installed  :
* OpenCL activated  : no
* Xorg              : 21.1.8
* Desktop           : Cinnamon 5.6.8
* GTK+              : 2.24.33-r3(2) and 3.24.37(3), ldd gives libgtk-3.so.0 => /usr/lib64/libgtk-3.so.0 (0x00007f108a200000)
* gcc               : 12.2.1_p20230428-r1
* cflags            : -march=native -O2 -pipe"
* CMAKE_BUILD_TYPE  :

**Additional context**
worked with the version compiled about a week ago

**Comment by koslowj** [comment]
The missing screenshot:
![screenshot](https://github.com/aurelienpierreeng/ansel/assets/33239207/cf749c9d-3027-4131-b146-d33d8e17a22c)

**Comment by Jiyone** [comment]
Those buttons have been moved to the global menu in "edit".

Closing as this is not an issue.

**Comment by koslowj** [comment]
OK, that's fine, but I haven't been able to find a changelog where this is mentioned.
