### ISSUE TITLE
Reorganisation of module titles in the darkroom

### ISSUE THREAD

**Issue by Joselpdj** [aurelienpierreeng/ansel#180]
**What is the current problem you are facing ?**
When I have to navigate between the different modules in the darkroom, this becomes tedious. Text is better than igonos, yes, but it would be a good idea to reorganise this so that I don't have to scroll back and forth so much to select the modules in the different sections.

**Where in your workflow does your problem occur ?**
Continuous scrolling left and right of the module sections (timeline, tone, colour, enque, etc.). 

**Additional context**
![foto](https://github.com/aurelienpierreeng/ansel/assets/65603208/1fd46599-84b8-4e3c-9747-12562079e3b4)

**Comment by Joselpdj** [comment]
This is just an idea, which after commenting on Matrix, may not be the most suitable, but it would be nice to have a better organised tab system than what we currently have. It's exhausting to have to scroll through all the tabs so many times...

**Comment by aurelienpierre** [comment]
If you need to scroll, then you are doing it wrong. If you stick to the intended workflow, there is no back-and-forth needed. Better fix your workflow than trying to make the GUI account for messy workflows.

In any case, Gtk doesn't support multiple lines as far as I know.

**Comment by Joselpdj** [comment]
I will try reorganize my workflow but I keep thinking that are a lot of titles for only one file...
