### ISSUE TITLE
Difficulty with making basic creative color adjustments

### ISSUE THREAD

**Issue by free41** [aurelienpierreeng/ansel#188]
**What is the current problem you are facing ?**

I'll start out by saying that I am very much a beginner photographer, and a beginner in post processing so if this problem can be solved just with better familiarization with existing tools, let me know. 

I am finding the workflow for making color adjustments difficult and long. Let's say I wanted to make adjustments based on hue in the original image. Things like desaturate "greens", shift "blues" toward cyan, etc. From what I understand there are two possible workflows. The color zones module can be used to make adjustments based on hue, but this is not recommended as "This module should be used with care, as transitions between colors may not be graceful." The other option is to use color balance RGB with parametric masks based on the hue range of interest.
 
**Where in your workflow does your problem occur ?**

Again I am a beginner, so I am attempting to follow some tutorials on color grading where they happen to use lightroom. It is pretty quick and easy to replicate the effects of "split toning" using a single instance of the color balance RGB module. But if I would like to emulate adjustments made to HSL sliders, I think I would need to make 7-8 instances of color balance RGB (with masks for each). One for red, green, blue, cyan, yellow, magenta, grays, etc.) For a beginner, that seems like a lot of work to make some basic adjustments to the image. 

The workflow is much faster in the color zones module where there is a preset which puts 8 control points on the curves that are roughly in the right position. I have found that this module does not give as good results as color balance RGB, and doesn't offer as much control (you can't choose between adjusting chroma or saturation as an example).

**Comment by pedrorrodriguez** [comment]
You can use color zones, but you have to be gentle with it. If the curve is too steep, or the adjustment too narrow, or both, you may end up creating visible artifacts. 

A new module has been in the works for a while aimed at replacing color zones. Atm there are other more urgent priorities, though, so in the meantime, you can either use several masked instances of color balance RGB or color zones.

**Comment by free41** [comment]
@pedrorrodriguez 

What is the other module/where is the work being done on it?

I wouldn't mind taking a look/helping out.
