### ISSUE TITLE
Quesstion and suggestion for "transitioning" page and Github intro

### ISSUE THREAD

**Issue by neocogent** [aurelienpierreeng/ansel#192]
I'm thinking of installing Ansel along side my current Darktable 3.8 install. I can't find any indications this is safe and/or what may happen if I do. I did look but I may have missed it. Will it use the same database or should I copy the database or must I start with fresh import and lose all past edits info? If I do start using with same database will it upgrade or change it? Is it safe in other words.

My suggestion is this info be added right at top of transitioning info page as that would be foremost on anyone using Darktable thinking of trying out Ansel - what steps should we do regarding database and how will it affect any current install whether pre-4.0 or latter. 

Since I'm still using 3.8 and have not migrated to 4.0+ I wonder if everything changes a lot. I already find some weird usability bugs but if it gets even worse then I very much like the idea of Ansel and I'm eager to try it as alternative to future Darktable use.

Thanks for looking at my input and if anyone has details on this query I'd appreciate guidance. And of course, Thanks for your work here on potentially my future platform.

**Comment by aurelienpierre** [comment]
> I can't find any indications this is safe and/or what may happen if I do. I did look but I may have missed it. Will it use the same database or should I copy the database or must I start with fresh import and lose all past edits info? If I do start using with same database will it upgrade or change it? Is it safe in other words.

See https://ansel.photos/en/doc/install/darktable/

In the future, you may peruse https://chantal.aurelienpierre.com/?s=from+darktable+to+ansel&github=False&forums=False&method=1#search-form

Otherwise, questions should be asked on https://community.ansel.photos, this is for bugs only.

**Comment by neocogent** [comment]
Thank you.
