### ISSUE TITLE
In Lighttable view the Filmstrip and Bottom bar won't show.

### ISSUE THREAD

**Issue by neocogent** [aurelienpierreeng/ansel#193]
In Lighttable view I cannot get Bottom bar to show or Filmstrip. This also means no way to use Culling or Preview. Also, the W and Ctrl-W seems to not work. According to doc pages I read these should be available. I also don't see any way to use Culling or Preview via a key shortcut. 

Filmstrip and bottom bar do show up in Darkroom view.

**To Reproduce**
In Lightroom press Ctrl-Shift-F - about half the time a flash at bottom of screen briefly show but not long enough to see hat it is. The other half nothing happens. Press Ctrl-Shift-B and nothing happens. Pressing W just says "w key not assigned". Same for Ctrl-W.

## Expected behavior
The bottom bar or the filmstrip will show up. I think cannot use Culling or Preview without bottom bar as cannot find hot-key equivalent.

## Which commit introduced the error
Unsure as first time trying app. The actual version is filename "Ansel-ff82b58-x86_64.AppImage", released earlier today as provided by download link on web site.

## System
Running on Mint 20.3 based on Ubuntu 20.04. (cinnamon version).

* Memory            : 12 GB
* Graphics card     : Intel Corporation 3rd Gen Core processor Graphics Controller
* Graphics driver   : unknown
* OpenCL installed  : none
* OpenCL activated  : none
* Xorg              : unknown
* Desktop           :
* GTK+              :
* gcc               :
* cflags            :
* CMAKE_BUILD_TYPE  :

**Additional context**
Works for me on Darktable 3.8.1 from default repository

**Comment by aurelienpierre** [comment]
Darktable culling mode has been removed, instead you will find a "selected" button in the filter toolbar (top). Select thumbnails and click it : the lighttable collection gets restricted to selected images. Click it again and the previous collection gets restored.

The filmstrip is available only in darkroom. You can toggle it ON/OFF with the global menu "Display" -> "Panels" -> "Filmstrip" where you will also find what key shortcut is assigned to it. If you imported the file `shortcutsrc` from darktable, then the key modifiers are not handled the same so you might need to reset the shortcuts (darktable shortcuts system handles Ctrl/Shift/Alt in a broken way, Ansel uses the default Gtk way).

**Comment by neocogent** [comment]
Oh. It might be an idea to update the docs to reflect the missing modes.

Relevant 3 pages here:
https://ansel.photos/en/doc/views/lighttable/lighttable-modes/

W and Ctrl-W feature here:
https://ansel.photos/en/doc/views/lighttable/

Ctrl-Shift B,F key functionality here:
https://ansel.photos/en/doc/overview/user-interface/

I primarily was checking out Ansel to try the post resampling sharpening in Export function so that I didn't need to do that after export in some other way. But honestly not having the Preview and culling/grouping etc may be more bothersome than missing that. So I've removed the program and will upgrade darktable instead. Thanks.

**Comment by aurelienpierre** [comment]
Culling and preview modes have been removed because they are technical debt coded with the ass, impossible to maintain with reasonable resources and responsible for slow-downs at the app level. 

Culling mode is done through the selected filter now. Preview is waiting for a full rewrite of the lighttable which was destroyed between 2019 and 2022 by incompetent amateurs.
