### ISSUE TITLE
Ansel build on Gentoo fails

### ISSUE THREAD

**Issue by TheMetMan** [aurelienpierreeng/ansel#195]
I am running Gentoo 6.4.3-gentoo-x86_64 #2 SMP PREEMPT_DYNAMIC Thu Jul 20 08:49:46 UTC 2023 x86_64 AMD Ryzen 7 5800 8-Core Processor AuthenticAMD GNU/Linux

## Description of the bug
`FAILED: bin/CMakeFiles/lib_ansel.dir/common/presets.c.o`
and
`FAILED: bin/CMakeFiles/lib_ansel.dir/common/styles.c.o`
Both these failures have the same error:
```
fatal error: libxml/encoding.h: No such file or directory
   28 | #include <libxml/encoding.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
However I do have libxml2 installed
```
**To Reproduce**
Attempting to build using this command on a fresh git clone.
`sh build.sh --build-type Release --install --sudo --clean-all`
This is commit ff82b588278f1e1234c947dc83296ffe194ec150 

## Expected behavior
Should build without failing

## System

* darktable version : Not Installed
* OS                : Gentoo Linux Kernel 6.4.3-gentoo-x86_64
* Linux - Distro    : Gentoo
* Memory            : 32Gb
* Graphics card     :  AMD Ryzen 7 5800 
* Graphics driver   : AMD Drivers
* OpenCL installed  : 2023.04.17
* OpenCL activated  : ??
* Xorg              :  21.1-r2
* Desktop           : KDE Plasma 5
* GTK+              : 3.24.38
* gcc               : 12.3.1_p20230526
* cflags            :  -march=znver3 -O2 -pipe
* CMAKE_BUILD_TYPE  : Release

**Additional context**
Build Log attached
[Build_Fail_2023-07-24.odt](https://github.com/aurelienpierreeng/ansel/files/12143234/Build_Fail_2023-07-24.odt)

**Comment by AlynxZhou** [comment]
Could you try manually `mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=~/usr -DCMAKE_INSTALL_LIBDIR=lib64 -DCMAKE_INSTALL_LIBEXECDIR=lib64 -DCMAKE_BUILD_TYPE=Release -DBINARY_PACKAGE_BUILD=1 -DBUILD_USERMANUAL=False -DUSE_LIBSECRET=ON -DUSE_LUA=ON -DBUILD_CURVE_TOOLS=ON -DBUILD_NOISE_TOOLS=ON -DRAWSPEED_ENABLE_LTO=ON -DBUILD_TESTING=OFF .. && make`?

Also, are you sure you have this header file in `/usr/include/libxml2`? Maybe some USE prevent from installing header files.

**Comment by TheMetMan** [comment]
Yeh!! That worked. I then installed with sudo make install command.
I do have the encoding.h file in /usr/include/libxml2/libxml/
Many thanks for the quick response.
I can now work away and see how this compares to Darktable. I shoot InfraRed in RAW by the way.
Best Regards

**Comment by AlynxZhou** [comment]
Then I think maybe some command is wrong in the build script, I typically don't use it because I just run build tools when packaging. Maybe Aurelien could fix it, but currently he is busy.

**Comment by stefantalpalaru** [comment]
I have packaged media-gfx/ansel in my overlay: https://github.com/stefantalpalaru/gentoo-overlay

**Comment by aurelienpierre** [comment]
Should be fixed now ? Re-open if not.

**Comment by TheMetMan** [comment]
Thank you Aurélien, this now build fine on Gentoo.
Regards
