### ISSUE TITLE
"Open from disk..." overwrites existing .xmp 

### ISSUE THREAD

**Issue by lukadh** [aurelienpierreeng/ansel#199]
## Description of the bug

Re-importing images that were previously edited in Ansel and then removed via "Remove Filmroll" results in "fresh" .xmp-files and therefore in loosing all edits and ratings.

**To Reproduce**

1. Edit an image in your Ansel library.
2. Remove that image from the library. 
3. Re-Import the image via "Open from disk..."
4. Take note, that your edits are gone.
5. Check the creation date of the corresponding .xmp-file in your file explorer

## Expected behavior

Read the .xmp when re-importing instead of replacing it with a new empty file.

## Which commit introduced the error

I'm guessing it is the latest commit ff82b58 , because it changes import behaviour and I'm building without the Lightroom Option.

## System

* darktable version : Ansel ff82b58
* OS                : Linux Pop_OS

**Comment by Markfas** [comment]
I can confirm this bug - running same version on same OS. 

Maybe related: when copying images via the export module (1:1) the related xmp files are left with the original. Shouldn't the xmp files be copied as well?

**Comment by Remy1959** [comment]
Bonjour

J'ai la même chose depuis le téléchargement et l'utilisation de la version ff82b58-x86_64
Je suis revenu à la version antérieure 7c9a129-x86_64 qui fonctionne normalement

**Comment by aurelienpierre** [comment]
Should be "fixed" by https://github.com/aurelienpierreeng/ansel/commit/45effc7447678ff38f2bcd62a4e54d94069de5b4 today.

**Comment by Markfas** [comment]
Thank you so much!

----------------------------------------

28.08.2023 11:36:54 Aurélien PIERRE ***@***.***>:

**Comment by lukadh** [comment]
Thanks, this one was important to me. I was just waiting for me to screw up my library 😅

**Comment by Remy1959** [comment]
Merci beaucoup
