### ISSUE TITLE
Make views optional

### ISSUE THREAD

**Issue by aurelienpierre** [aurelienpierreeng/ansel#20]
The map, printing and slideshow views are niche features used only by a minority of users. Problem is, they are still enabled for all users. Gtk widgets are drawn and therefore computed as soon as they are declared in UI, no matter if they are visible or not for the end-user. That's CPU cycles lost for everyone. Especially for the map view, which might be loading map tiles from the internet (or not).

Solution: make map, printing and slideshow views available only optionaly. If disabled, they will not even be declared and initialized in UI (will require a restart).

**Comment by mediatechnologic** [comment]
The best workflow is to separate the software for DAM, Editing, Slideshow, Printing, Mapviews … VERY strictly.
With this you can select the best tool for every task and you have to adjust the use of metadata in this workflow.
The idea to have all-in-one tools is a dead-end-street and reduces the freedom of users too much.
And the programmer can not concentrate on the main topic any more.
Thank you Aurelien for keeping R-DT concentrating on basics and targeting for KISS.

**Comment by aurelienpierre** [comment]
Done in master.
