### ISSUE TITLE
No english translation of main menu toolbar category "ateliers"

### ISSUE THREAD

**Issue by chambers** [aurelienpierreeng/ansel#207]
## Description of the bug

It's a small thing in the grand scheme of things. Menu category is listed as "ateliers". The sub-items are Lighttable and Darkroom 

## Suggested fix

Change to "Modes", "Workshops" or "Studios". I prefer modes.

**Comment by lukadh** [comment]
Hey @chambers,

that naming is actually a concious decision. The word _atelier_ actually also [exists also in English](https://www.dictionary.com/browse/atelier). I know what you mean though. Then again I'm not a native speaker...

**Comment by chambers** [comment]
The stated intended purpose of this fork was to remove some unnecessary bloat and to make UI and usability improvements. Using "ateliers" in this case is even more esoteric than using that weird intersection symbol that comes from set theory or whatever.

**Comment by lukadh** [comment]
Yeah, I also think it is a bit cryptic, but Aurélien seems to really like it. So I guess it will stay and as you said yourself I try to accept it as a rather small thing in the grand scheme.

**Comment by pedrorrodriguez** [comment]
https://www.merriam-webster.com/dictionary/atelier

**Comment by johnwoltman** [comment]
As a _competent_ native English speaker (_college_-educted), I've never _encountered_ "atelier" outside of Ansel. If Ansel is supposed to be a better Darktable, I _propose_ that _insisting_ on such an _unfamiliar_ word is a bit of _faux pas_.  French's _influence_ on English is _profound_, but I think there's a very good UI/UX _argument_ that "atelier" should be _replaced_ in the English _version_.  The very first thing I thought when I launched Ansel was "oops someone forgot to translate this, what the heck does ateliers mean?"

(Did you see what I did there?)

**Comment by chambers** [comment]
Touché
