### ISSUE TITLE
write metadata to xmp sidecar file

### ISSUE THREAD

**Issue by daimonnomos** [aurelienpierreeng/ansel#209]
## Description of the bug

In Ansel version: eb70788 (win64), metadata is not written to a xmp sidecar file (anymore). The metadata is saved in the database.
the Ansel preferences-storage are checked and are not changed. The value for 'write sidecarfile for each image' is set to 'after edit'
Reinstallation of previous version ( 43e4fce win64) solves this problem.

**To Reproduce**

add ,edit or remove text in the 'Edit text tags' tab.

## Expected behavior
save metadata to xmp sidecar file

## Context

lighttable

**Screenshots**

**Screencast**

## Which commit introduced the error

version: eb70788

## System

OS Name	Microsoft Windows 10 Pro
and
OS Name	Microsoft Windows 11 home

**Additional context**

 - Can you reproduce with another Ansel version(s)? no
 - Can you reproduce with a RAW or Jpeg or both? **both
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes
 - Is the issue still present using an empty/new config-dir (e.g. start Ansel with --configdir "/tmp")? **yes
 - Do you use lua scripts?**no

**Comment by CendaL** [comment]
I do see the bug too.
cc @Jiyone and @cloveryapps for #205

**Comment by bridge-men** [comment]
Same happens here after reinstall linux mint 21.2 and rebuild ansel eb70788.

**Comment by bridge-men** [comment]
Using Ansel-3b08349-x86_64.AppImage, writes xmp-files, earlier versions not tested.

**Comment by aurelienpierre** [comment]
Should be fixed now, feel free to re-open if it's not.
