### ISSUE TITLE
Crash on Export

### ISSUE THREAD

**Issue by audiomartin** [aurelienpierreeng/ansel#214]
## Description of the bug

Ansel crashes while exporting an image.

Developed picture ready for export. Set Export settings, press "Export", PC starts calculating, some seconds later Error warning and Crash

## Expected behavior

Export picture.

## Context

see attached xmp.

## System

Win10, i7-2600, Geforce GTX 1050ti

Ansel 43e4fce + Ansel eb70788

**Additional context**

Crash happens with Darktable 4.0.0 aswell. Other pictures from that camera are export as expected. (The picture is not that bad. ;-)

Crash reports and xmp attached. 

As I like using Ansel a lot for my work I hope that report might help to make Ansel even better. 

AtB audiomartin 
[Ansel crash reports xmp.zip](https://github.com/aurelienpierreeng/ansel/files/13187126/Ansel.crash.reports.xmp.zip)

**Comment by aurelienpierre** [comment]
The crash reports are empty and I don't have your file. Seeing that it's a CR3, it might be an issue in Libraw.

**Comment by audiomartin** [comment]
Running now 082cb86, there are no more problems with this file. Export works flawless. 
I am using mostly .cr3 with Ansel, except the one above, I had never any issues. 
AtB martin
