### ISSUE TITLE
Star rating not working / showing

### ISSUE THREAD

**Issue by nitschis** [aurelienpierreeng/ansel#216]
I see no option to set a star rating on pictures. It is not below the picture, and hotkeys 1-5 do also not work.

I have tried the most current appimage and built from source. I have also tried older appimages with the same result.

**To Reproduce**

1. Load CR3 Raw
2. No stars are shown

**Screenshots**

![Screenshot_20231107_011115](https://github.com/aurelienpierreeng/ansel/assets/62210453/f359555e-c7d0-4c65-9a6b-46e8586d26b1)

## System

* darktable version :  Ansel-06d9cda-x86_64 
* OS                : Linux - kernel 6.5
* Linux - Distro    : Manjaro KDE
* Memory            : 32GB
* Graphics card     : AMD 6900XT

**Comment by pedrorrodriguez** [comment]
Go to the global menu. Display - Thumbnail overlays

**Comment by nitschis** [comment]
Thank you, the stars are now showing. However, the hotkeys still do not work.

**Comment by nitschis** [comment]
Okay, very strange behavior. I manually set a color label and star on an image, since then shortcuts started working.. There still seems to be a bug here, but I will close the issue.

**Comment by pedrorrodriguez** [comment]
> Okay, very strange behavior. I manually set a color label and star on an image, since then shortcuts started working.. There still seems to be a bug here, but I will close the issue.
> 
> Edit: I tried with a freshly installed AppImage and deleting the config folder. I could reproduce this error. I had to enable and disable a color filter before shortcuts started working.

The whole lighttable is being rewritten to fix shortcuts and selection issues.

**Comment by barathrm** [comment]
Could we reopen this? I just hit the same. Fresh install of `7f23d9d3` and ratings seemed to not work, neither shortcuts nor manually using the overlays + mouse clicks. Randomly enabling and disabling a color filter seems to have fixed it and now I can rate images.

**Comment by TheMetMan** [comment]
I am having the same problem with the Compiled version 417802a in Gentoo Linux. the Rating is not displayed and the number keys (top of keyboard and right hand side) do not change the rating.
However the AppImage Version 0.0.0+1240~gd88ee95e is working as expected.
Then blow me down, having used the rating in  the AppImage, the compiled version worked!!
