### ISSUE TITLE
Missing clones actions

### ISSUE THREAD

**Issue by tflorac** [aurelienpierreeng/ansel#218]
## Description of the bug

I'm using release 0.0.0+394~g06d9cda32 of Ansel, built from sources on Debian GNU/Linux "testing".
When looking at the clones management portlet, I don't have action button to create a new clone:

![image](https://github.com/aurelienpierreeng/ansel/assets/326159/ba6d9f56-ccb5-4fba-94be-a35e8822ab54)

## Expected behavior

Have buttons to create new clones (from original or as a copy of the current development image).

## System

* darktable version : 0.0.0+394~g06d9cda32
* OS                : Debian GNU/Linux - kernel 6.5.0
* Linux - Distro    : Debian Trixie (testing)
* Memory            : 24 GB
* Graphics card     : AMD Radeon R9 380
* Graphics driver   : AMD Gpupro
* OpenCL installed  : no
* OpenCL activated  : no
* Xorg              : Wayland
* Desktop           : GNOME 44.5

**Comment by lukadh** [comment]
Hey @tflorac,

those actions have been moved to "Edit" in the global menu.

**Comment by tflorac** [comment]
Hey @lukadh ,
Do you know why some commands (like history compression for example) are still available in the menu and in the side panel (which can be quite practical in my own opinion), while other ones are only in the menu?
