### ISSUE TITLE
XMP File Location

### ISSUE THREAD

**Issue by dnlyko** [aurelienpierreeng/ansel#219]
The XMP files are not being saved in the original picture file folder.
It works on 43e4fcex, but not after.

Is this by design, if so, where are the XMP files being saved to ?

 System
* OS                : Windows11
* Memory            :64GB
* Graphics card     :RTX3060
* Graphics driver   :
* OpenCL installed  :Yes
* OpenCL activated  :Yes

**Comment by AlynxZhou** [comment]
I also noticed this, not sure whether this is a bug or by-design too.

**Comment by lukadh** [comment]
Hmm I'm using f7669af, built myself under Ubuntu and .xmp files are being saved in the image folder. 

To quote @aurelienpierre (matrix chat, 18. November 2023):
"The XMP are saved along the images, nothing has changed here
if they are not then we have a problem"

**Comment by dnlyko** [comment]
This has been fixed
