### ISSUE TITLE
Missing checkbox labels when using `Open from disk` dialog

### ISSUE THREAD

**Issue by Quintasan** [aurelienpierreeng/ansel#225]
## Description of the bug

Two checkboxes are missing their labels when importing files from disk.

**To Reproduce**

1. I'm running build `f7669af` with language manually changed to English
1. Click on `Open from disk...` button in the `Open & import` section on the left

## Expected behavior

All checkboxes have labels.

## Context

**Screenshots**

![ansel_PhUZi6wCIQ](https://github.com/aurelienpierreeng/ansel/assets/6539261/91848437-4adb-42ba-8a53-0d8aeafcb121)

**Comment by aurelienpierre** [comment]
Import popup got rewritten.
