### ISSUE TITLE
Metadata import breaks when german Umlauts in folder name (e.g. ö)

### ISSUE THREAD

**Issue by merschs** [aurelienpierreeng/ansel#228]
## Description of the bug

When importing a folder the jpg metadata is not matched to the corresponding raw file, if there is Umlaut (e.g., ö) in the folder name.

**To Reproduce**

1. Go to Import
2. Select folder with Umlaut (e.g, ö)
3. Import
4. See metadata is empty (no exposure, camera brand, etc.)

## Expected behavior
Just like importing from any other folder (i.e., raws having metadata)

## Context
[import.zip](https://github.com/aurelienpierreeng/ansel/files/13467319/import.zip)

## Which commit introduced the error
Using prepackaged Windows Builds, the first broken version is this: 
 ansel-eb70788-win64.exe 

Meaning, it is working in version: 
ansel-43e4fce-win64.exe 

## System
Windows system

**Additional context**
Reproducable with all newer versions newer than the first broken version ansel-eb70788-win64.exe.

**Comment by aurelienpierre** [comment]
See https://github.com/aurelienpierreeng/ansel/issues/231 for a workaround, this issue is with Exiv2
