### ISSUE TITLE
No more Exifdata?

### ISSUE THREAD

**Issue by audiomartin** [aurelienpierreeng/ansel#231]
Hi there,

I do not see the information about aperture, focal length, etc. of my .cr3 files anymore.

## Expected behavior
See relevant data.  In some older version of Ansel this was possible (as far as I remember), usefull for corrections, Denoise, Lens Correction,... 

![Clipboard02](https://github.com/aurelienpierreeng/ansel/assets/43499366/85662adb-ca7c-46d5-a514-4594c64cb1f1)
![Clipboard01](https://github.com/aurelienpierreeng/ansel/assets/43499366/76e4b13d-6493-4ef0-aeff-b24a8439e2fa)

## System
Win10, i7-2600, Geforce GTX 1050ti
Ansel 6f72fc9

All the Best 
audiomartin

**Comment by aurelienpierre** [comment]
Can you send an affected CR3 file ?

**Comment by aurelienpierre** [comment]
I tried your file and I get an Exiv2 error. Are you sure it's supported by Exiv2 ?

**Comment by aurelienpierre** [comment]
Ok, I needed to rebuild Exiv with ISOBMFF support and it finally worked. Seems supported on Linux…

**Comment by audiomartin** [comment]
Thanks for taking care!

Still the same with latest version bf804ef of Ansel on Win10. 

> https://github.com/aurelienpierreeng/ansel/issues/231#issuecomment-1832746980

It is an Eos R5, worked before up to now. With Pictures imported before version 6f72fc9 the Exifdata is still visible.


m.

**Comment by aurelienpierre** [comment]
Your last working version was built using `mingw-w64-ucrt-x86_64-exiv2-0.28.1-1` and the new ones are built using `mingw-w64-ucrt-x86_64-exiv2-0.28.1-2`, so I guess something is wrong in the Win Exiv2 package

**Comment by aurelienpierre** [comment]
Your last working version was built using `mingw-w64-ucrt-x86_64-exiv2-0.28.1-1` and the new ones are built using `mingw-w64-ucrt-x86_64-exiv2-0.28.1-2`, so I guess something is wrong in the Win Exiv2 package

**Comment by audiomartin** [comment]
There might be some hints for a developer, for me it is far beyond me knowledge:

[https://github.com/darktable-org/darktable/issues/15478#issue-1959660414](url)

and 

[https://github.com/Exiv2/exiv2/issues/2637#issue-1729310589](url)

You probably already found it yourself.

m.

**Comment by aurelienpierre** [comment]
Also @AlynxZhou found this [commit](https://github.com/msys2/MINGW-packages/commit/caf91ef399c52c0d1e927e0b30e6864d4c44bccb#diff-999e140702141b61cae6ee14fe426b5becbe0e0c33c0c809060d7fb00825aa23L52) on MingW build script that drops explicit support of ISOBMFF in Exiv2, relying on whatever defaults the CMakeList.txt of the project is using.

**Comment by AlynxZhou** [comment]
@audiomartin Did you put your CR3 files in a path contains non-ASCII chars?

**Comment by audiomartin** [comment]
YES! 
For testing i made a folder without _Umlaut_, it works! All exif data is visible. 
Great Guys. For the moment i will rename my folders without _Umlaut_.
Thanks for the hints. 
m.

**Comment by aurelienpierre** [comment]
Bitte _schön_ :D

**Comment by audiomartin** [comment]
Danke schÖn.

@AlynxZhou 
No problem, just have to remember dropping my äöü. :-)
