### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by EricBright** [aurelienpierreeng/ansel#233]
## Description of the bug

Ansel 3c8f896 reporting an exception

**To Reproduce**

1. Install Ansel 3c8f896 or any older build
2. Run Ansel
3. After a few seconds, an exception message will pop up
4. Click on the 'OK' button in the message
5. The program terminates and writes a log in the following location: C:\Users\[...]\AppData\Local\Temp (7 of them are attached)

## Expected behavior

1. Install Ansel 3c8f896 or any older build
2. Run Ansel
3. The software opens and is ready to be used

## Context

n/a

**Screenshots**

![Screenshot 2023-11-28 125334](https://github.com/aurelienpierreeng/ansel/assets/3061070/49f7d398-3043-4e33-b46c-2e6f5bb3fb8a)

## Which commit introduced the error
Tried 3c8f896 and a few older versions, including the first Win64 version. None would start. All will show the same exception message.

## System

* darktable version : n/a
* Ansel versin: 3c8f896
* OS                : Windows 10.0.19041.3636
* Memory            :
* Graphics card     : NVIDIA GeForce RTX 4060 Ti
* Graphics driver   : Game Ready Driver version 546.17
* OpenCL installed  : yes
* OpenCL activated  : yes
* Xorg              : n/a
* Desktop           : n/a
* GTK+              : ?
* gcc               : ?
* cflags            : ?
* CMAKE_BUILD_TYPE  : ?

**Additional context**

 - Can you reproduce with another darktable [<-- needs to be replaced by ansel] version(s)? **yes with all previous versions**
 - Can you reproduce with a RAW or Jpeg or both? n/a
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes** or n/a
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes** or n/a
 - Do you use lua scripts? no

Retrieved logs:

[ansel_bt_2HACF2.txt](https://github.com/aurelienpierreeng/ansel/files/13491098/ansel_bt_2HACF2.txt)
[ansel_bt_AFWBF2.txt](https://github.com/aurelienpierreeng/ansel/files/13491099/ansel_bt_AFWBF2.txt)
[ansel_bt_DCE6E2.txt](https://github.com/aurelienpierreeng/ansel/files/13491100/ansel_bt_DCE6E2.txt)
[ansel_bt_KT57E2.txt](https://github.com/aurelienpierreeng/ansel/files/13491101/ansel_bt_KT57E2.txt)
[ansel_bt_NII0E2.txt](https://github.com/aurelienpierreeng/ansel/files/13491102/ansel_bt_NII0E2.txt)
[ansel_bt_UGGXE2.txt](https://github.com/aurelienpierreeng/ansel/files/13491103/ansel_bt_UGGXE2.txt)
[ansel_bt_UUYCF2.txt](https://github.com/aurelienpierreeng/ansel/files/13491104/ansel_bt_UUYCF2.txt)

**Comment by aurelienpierre** [comment]
This is an issue with your OpenCL driver. Try removing, reinstalling or downgrading it.

**Comment by aurelienpierre** [comment]
@dnlyko your issue is different, it's with dtgtk_toggle_button. Please open a different issue.

**Comment by pedrorrodriguez** [comment]
@EricBright Please confirm whether the solution given by @aurelienpierre works

**Comment by EricBright** [comment]
OpenCL does now have an individual installer on my PC. It seems to be part of another package. Since I have several other software that rely on the performance of my graphic card and OpenCL, I won't be able to downgrade any of the drivers (previous graphic card drivers were causes of frequent BSOD on my box, which I cannot afford to re-experience).

There was, however, this package that I temporarily uninstalled with no positive outcome: OpenCL™ and OpenGL® Compatibility Pack.

At any rate, thank you for looking into the error! 🙏🏽 If it cannot be fixed, then that is that.

**Comment by aurelienpierre** [comment]
For future reference:

```
ansel.exe caused an Access Violation at location 00007FF9E686385F in module CLOn12Compiler.dll Writing to location 0000000000000008.

AddrPC           Params
00007FF9E686385F 00000208E21BD3A0 000000C6471FC300 00000208AF42EED8  CLOn12Compiler.dll!clc_libclc_new_dxil+0x7bf
00007FF9E68649A1 0000000000000001 00007FFA9E4F0000 0000000000000000  CLOn12Compiler.dll!clc_spirv_to_dxil+0xb11
00007FFA3F049A2D 0000000000000000 00000208E10CB7D8 00000208AE3A8770  OpenCLOn12.dll!0x9a2d
00007FFA3F06BAEA 0000000000000000 00000208F5C65160 00000208AD2DD0F0  OpenCLOn12.dll!clUnloadPlatformCompiler+0x5f8a
00007FFA3F06A798 0000020800000000 0000000000000000 00000208E11D9398  OpenCLOn12.dll!clUnloadPlatformCompiler+0x4c38
00007FFA3F06A24F 00000208E24F9AD0 000000C6471FEA18 00000208E169B800  OpenCLOn12.dll!clUnloadPlatformCompiler+0x46ef
00007FFA3F06E20C 00000208E11D9340 0000000000002500 0000000000000000  OpenCLOn12.dll!clBuildProgram+0x17c
00007FFA122C7751 00000208E2103C90 0000000000000000 00000208E1584350  libansel.dll!dt_opencl_build_program+0x91
00007FFA122CDCDF 00000208E1721920 0000000000000000 0000000000000000  libansel.dll!dt_opencl_init+0x253f
00007FFA12229E79 00007FFA00000001 00000208DEBD66F0 0000000000000001  libansel.dll!dt_init+0xd09
00007FF73D8A2CEB 00007FF73D8A1560 00007FF73D8A277D 00007FFA9C0A1270  ansel.exe!0x2ceb
00007FF73D8A14C2 0000000000000000 00007FF73D8A7048 0000000000000000  ansel.exe!0x14c2
00007FF73D8A12F7 0000000000000000 0000000000000000 0000000000000000  ansel.exe!0x12f7
00007FF73D8A1406 0000000000000000 0000000000000000 0000000000000000  ansel.exe!0x1406
00007FFA9CB57344 0000000000000000 0000000000000000 0000000000000000  KERNEL32.DLL!BaseThreadInitThunk+0x14
00007FFA9E5426B1 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart+0x21
```

You will need to start the software with OpenCL disabled if you can't downgrade the GPU driver. But as I said, what you have is really really new version of the driver (november 14th 2023) so I highly doubt that whatever app you have requiring GPU drivers will not be able to work with slightly older and more stable drivers. You can try https://www.nvidia.fr/download/driverResults.aspx/217056/fr
