### ISSUE TITLE
Image is black in Lightroom (and also after export it), while in Darkroom is processed properly

### ISSUE THREAD

**Issue by LucaZulberti** [aurelienpierreeng/ansel#236]
## Description of the bug

Today I have updated to 0.0.0+494~g9e5c5285b on Ubuntu 22.04. I modified one photo and when I switched back to Lightroom, the image is black.
If I go back again to Darkroom, the image is processed correctly.

**To Reproduce**

1. Go to 'Lightroom'
2. Double click on one photo to open 'Darkroom'
3. Apply 'crop'
4. Close 'Darkroom'

## Expected behavior
Image cropped correctly also in Lightoom view

## Context

[image_plus_xmp.zip](https://github.com/aurelienpierreeng/ansel/files/13533954/image_plus_xmp.zip)

**Screenshots**
![immagine](https://github.com/aurelienpierreeng/ansel/assets/8284106/3fdfa738-aebe-40e7-b51a-860f24b17804)

## Which commit introduced the error

a95375f5780fb953492ed0746ecc3d59bc2af1b2 is the first bad commit

## System

* darktable version : e.g. 3.5.0+250~gee17c5dcc
* OS                : Linux 6.2.0-37-generic #38~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC x86_64 x86_64 x86_64 GNU/Linux
* Linux - Distro    : Ubuntu 22.04
* Memory            : 16 GB
* Graphics card     : Radeon HD 7000
* Graphics driver   : AMD
* OpenCL installed  : ROCr
* OpenCL activated  : unknown
* Xorg              : unknown
* Desktop           : wayland
* GTK+              : 3.24.33
* gcc               : 12.3.0
* cflags            : unknown
* CMAKE_BUILD_TYPE  : Release

**Additional context**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? YES
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? YES

**Comment by aurelienpierre** [comment]
Yep, I know. WIP

**Comment by aurelienpierre** [comment]
Fixed by 69ceae1b44835c6612a814508a8c3e097b10162f
