### ISSUE TITLE
Target middle-grey doesn't automatically adjust relative to target white luminance in filmic. Instax printer workflow.

### ISSUE THREAD

**Issue by pedrorrodriguez** [aurelienpierreeng/ansel#24]
**What is the current problem you are facing ?**

Target middle-grey stays the same when changing target white luminance inside the display tab of filmic when preparing images for printing on Instax printer. Ideally for my usecase it would automatically adjust relative to the target white luminance.

EDIT: after thinking some more about it, my real issue is fitting my picture into the DR of my printer easily, while being able to save that as a preset. How that's done is not very important to me. 

**Where in your workflow does your problem occur ?**

Let me start by saying that I'm not sure if this is the right way to go about what I want to do. If not, please let me know what the best way to deal with this is, although it seems like this is what filmic is for, compressing the DR to fit the target medium.

Let me elaborate, I have an instax printer that I like to use for printing candid shots with family and friends. It's a lot of fun, but the DR of the film is not huge, and I need to compress it quite a bit to make it fit (not blow the highlights on the film). I've been handling this via tone equalizer, at first, although I've recently tried the display tab inside filmic, lowering the target white luminance as needed, which seems like the way to go. The problem: the target middle-grey stays the same. 

I can easily figure out what the target middle grey should be relative to the target white luminance, although it would be nice if this could be automatic.

**My instax workflow:**

Edit my picture as usual. Lower target white luminance. Figure out target middle-grey value. Change contrast in highlights and shadows from hard to safe so they don't overshoot.

**Comment by aurelienpierre** [comment]
I think you are taking the problem reversed. For reflective media, you leave white and grey where they are, it's the black point that you should raise as to match the bottom of the dynamic range. That should properly brighten the shadows.

Auto black point compensation (from ICC profile) is planned for filmic v7.

**Comment by pedrorrodriguez** [comment]
> I think you are taking the problem reversed. For reflective media, you leave white and grey where they are, it's the black point that you should raise as to match the bottom of the dynamic range. That should properly brighten the shadows.

I understand that that would be the case for normal printers. However for instax, there is no ICC profile, and if you leave your highlights where they look good on your monitor they will clip on the instax film. In my testing, highlights shouldn't go much above 60% luminance. It's not just my printer, there are blog posts online telling you to drop contrast and brightness via the instax app to protect the highlights.

https://fstoppers.com/originals/fstoppers-reviews-fujifilm-instax-share-sp-3-smartphone-printer-291657 

> Auto black point compensation (from ICC profile) is planned for filmic v7.

That's great news! Fantastic to hear!

**Comment by aurelienpierre** [comment]
The thing is, if there is no ICC profile documenting the max allowed luminance, I can't make anything automatic here. 

I'm not sure lowering the middle grey is a good way to go since it will essentially darken the whole pic. I guess the only option is to have a filmic preset with "display white level" set at 60%.

**Comment by pedrorrodriguez** [comment]
> I'm not sure lowering the middle grey is a good way to go since it will essentially darken the whole pic. I guess the only option is to have a filmic preset with "display white level" set at 60%.

That was my initial thought, and it probably would work well on other (more professional) printers. This is basically a toy, after all. However, if I just lower the "display white level" level to 60% without adjusting (lowering) middle grey, everything above middle grey gets extremely compressed, ruining contrast, and thus my picture. If the printer/film works only between let's say 1-60% of the screen's brightness, keeping middle grey at 18% relative to my screen doesn't make sense. I think it should be 18% of the target medium, shouldn't it? 

As you said, I can easily make a preset if this doesn't make sense to you.

**Comment by pedrorrodriguez** [comment]
I'm gonna close this issue. Setting the white/black relative exposure to their max values (via right click) and setting the contrast in highlights/shadows to "safe" gives the best results so far for my Instax SP-3.
