### ISSUE TITLE
Setting not updated in darkroom when dragging sliders until mouse button released / clicked

### ISSUE THREAD

**Issue by pjhyor7** [aurelienpierreeng/ansel#247]
## Description of the bug

When dragging a slider to adjust a setting in darkroom, the setting is not applied until the mouse is let go.
From what I have tested, this applies to all sliders. 

This bug also occurs when right clicking and moving the slider setting.

**To Reproduce**

1. Click on global variance slider
2. Drag slider to increase or decrease setting, but do not let go of mouse button
3. Error is that the changed setting is not applied to image
4. Let go of mouse button
5. Setting is now applied to image

1. Right click on global variance slider
2. Move mouse to increase or decrease setting
3. Error is that the changed setting is not applied to image
4. Click mouse button
5. Setting is now applied to image

## Expected behavior

While dragging a slider, the image should apply in real-time for immediate feedback of the change's effect.

## System

* darktable version : d825e81
* OS                :  Windows 10 (build 19045)
* Memory            : 24576mb
* Graphics card     : AMD Radeon R9 200
* OpenCL installed  : Yes
* OpenCL activated  : Yes

**Comment by Jiyone** [comment]
Hi!
This change has been, made on purpose.
you can right-clic to show the precision popup, and hold left-clic inside it while you move the cursor to continuously change the setting. You can also use the mouse wheel while your cursor overlaps the setting.

**Comment by pjhyor7** [comment]
> Hi! This change has been, made on purpose. you can right-clic to show the precision popup, and hold the left mouse button clicked inside it while you move the cursor to continuously change the setting. You can also use the mouse wheel while your cursor overlaps the setting.

Ah thank you. I didn't realise this was a purpose change. Thank you for the clarifying about how I can still see the changes real-time still.
