### ISSUE TITLE
Crash changing view (ansel-96f0d97-win64.exe ) after update

### ISSUE THREAD

**Issue by audiomartin** [aurelienpierreeng/ansel#249]
## Description of the bug

Opening Ansel, it starts in latest state of view, here Lighttable without sidepanels, picture size maximized (only one picture). The upgrade from ansel-d825e81-win64.exe to the latest ansel-96f0d97-win64.exe does not allow to bring back the side panels, it crashes. 

**To Reproduce**

Leave Ansel d825e... in Lighttable View without side panel pictue to max. size
Update from ansel-d825e81-win64.exe to ansel-96f0d97-win64.exe, open Ansel. TAB to open side panels. Crash note.

When leaving ansel-d825e81-win64.exe in Lighttable view with sidepanels and multiple pictures. Update to and start Ansel 96f0d97... TAB to change view of sidepanels crashes too.

## Expected behavior

Change view of sidepanels in Lighttable view by pressing TAB.

## System

Win10, i7-2600, Geforce GTX 1050ti
ansel-96f0d97-win64.exe

[ansel_bt_YZWQF2.txt](https://github.com/aurelienpierreeng/ansel/files/13578334/ansel_bt_YZWQF2.txt)

**Comment by aurelienpierre** [comment]
Fixed now ?

**Comment by audiomartin** [comment]
It is no more an issue since next version. Thanks a lot.
