### ISSUE TITLE
Non-raw images issue in Version ansel-1dbee19-win64

### ISSUE THREAD

**Issue by audiomartin** [aurelienpierreeng/ansel#260]
## Description of the bug

Trying to open files developed in older version (up to d825e81-win64) with negadoctor in Darkroom Atelier Ansel stucks in loop. I have to force stop Ansel.
Happens to all images developed with Negadoctor.

Win10, i7-2600, Geforce GTX 1050ti
ansel-1dbee19-win64

**Comment by aurelienpierre** [comment]
Can you start the program in terminal with `-d all` and give the output ?

**Comment by Jiyone** [comment]
I don't reproduce on ubuntu 22.04. Using the last commit 1dbee19.
You should give us more information. What do you do exactly? Are you using the Appimage? Do you build Ansel? If yes, how?

**Comment by audiomartin** [comment]
1. [ansel-log.txt](https://github.com/aurelienpierreeng/ansel/files/13614995/ansel-log.txt)

2. 
Start Ansel, which opens in Lighttable Atelier. 
Choose Folder from Library panel. Choose Picture in Center Panel
Double Click left Mouse Button on Image (.tiff) from collection, which had been developed in an older version of Ansel with Negadoctor module. (This happens only to pictures with Negadoctor module in the pipeline.)
Ansel gets stucked.

Running ansel-1dbee19-win64.exe on Windows 10, i7-2600, Geforce GTX 1050ti.

No, i do not build myself.

Hope this helps.

**Comment by aurelienpierre** [comment]
Are your files DNG ?

**Comment by audiomartin** [comment]
No DNGs here. Only TIFs from Scanners.
I give some TIFs without Negadoctor a try.

**Comment by aurelienpierre** [comment]
Not until you confirm the the fix fixed it

**Comment by audiomartin** [comment]
As it is not related only to Negadoctor module, but for non-raw images handling?

**Comment by aurelienpierre** [comment]
yes

**Comment by audiomartin** [comment]
:+1:

**Comment by aurelienpierre** [comment]
Fixed ?
