### ISSUE TITLE
Add more crop presets to the crop module

### ISSUE THREAD

**Issue by pedrorrodriguez** [aurelienpierreeng/ansel#273]
Since you are working on the crop module, I went over the aspect ratios, organized them, added a few more, fixed some errors, capitalization, and added some comments. Maybe not all are necessary, but the dimensions are not made up. They new additions come from the sizes Ilford makes their sheet film in. Also fixed the cinema aspect ratios.

- Freehand
- Original image
- Square (1x1, 6x6, 8x8, 14x14) = 1
- 6x7 = 1.167
- 5x6 (10x8 _in print_,10x12, 20x24) = 1.2  _(8x10 wrong in ansel preset. Its ratio is 1.2 instead of 1.25. Also, I have no idea what in print means)_
- 14x17 =1.214
- 4x5 (12x15, 16x20) = 1.25
- 11x14 =  1.273
- 8.5x11 (US letter) = 1.294 _(Unsure of the need for this one. Very close to the next one, and not a film aspect ratio)_
- 3.25x4.25 (6.5x8.5) = 1.307
- 4:3 (18x24, VGA, TV) = 1.333 _(Maybe remove VGA and TV?)_
- 4.75x6.5 = 1.368
- Academy ratio = 1.37
- 6.5x9 (13x18) = 1.385
- 5x7 = 1.4
- A4 (ISO 216, DIN476) = 1.41 _(maybe remove ISO 216, DIN476, since it's the same thing)__(Unsure of the need for this one. Very close to the previous and the next one, and not a film aspect ratio)_
- 14x20 = 1.428
- 2.25x3.25 = 1.445
- 3:2 (35mm film, 4x6, 6x9) = 1.5
- 7x11 = 1.571
- 5x8 (10x16) = 1.6
- Golden ratio = 1.618 _(changed it from "golden cut". Unsure if necessary, since it's really close to the previous one, and it's not a film aspect ratio, but alright)_
- 3x5 (12x20) = 1.667
- 8.5x15 = 1.765
- 16:9 (HDTV) = 1.778 
- Normal widescreen = 1.85 
- 2:1 (8x16, univisium) = 2 _(I would take out univisium. It has not been adopted, so nobody outside movie nerds will know about it)_
- 9x21 = 2.334 _(wrong in Ansel preset)_
- Cinemascope 3 = 2.35 _(Cinemascope 1-3 numbered in chronological order)_
- Anamorphic widescreen = 2.39
- 5x12 = 2.4
- 7x17 = 2.428
- 2x5 (4x10, 8x20) = 2.5
- Cinemascope 2 = 2.55
- Cinemascope 1 = 2.66
- 24x65 (Xpan) = 2.708
- Ultra-Panavision (70mm, IMAX) = 2.76 
- Panorama = 3
- Polyvision = 4

**Comment by aurelienpierre** [comment]
This is getting a bit out of hand though, I'm not sure the combobox would fit in height for smaller screens.

During work on the crop module, I discovered there is an hidden preference in `.config/ansel/anselrc` called `plugins/darkroom/clipping/extra_aspect_ratios`. You can add as many as you want, separated by `/`, with ratios defined as `width:height`.

**Comment by pedrorrodriguez** [comment]
Thanks for the tip! I will use it. 

The list is clearly too long. I just wanted to fix mistakes in the current one, and perhaps add a few new relevant ones. This is about having sane (and accurate) presets. Perhaps you disagree, but I would take out US Letter, A4, golden ratio, and all the cine aspect ratios. This is a photo editing app, after all. Having presets based on actual film dimensions I think is the right choice:


- Freehand
- Original image
- Square (1x1, 6x6, 8x8, 14x14) = 1
- 6x7 = 1.167
- 5x6 (8x10,10x12, 20x24) = 1.2 
- 14x17 =1.214
- 4x5 (12x15, 16x20) = 1.25
- 11x14 = 1.273
- 3.25x4.25 (6.5x8.5) = 1.307
- 4:3 (18x24) = 1.333 
- 4.75x6.5 = 1.368
- 6.5x9 (13x18) = 1.385
- 5x7 = 1.4
- 14x20 = 1.428
- 2.25x3.25 = 1.445
- 3:2 (35mm film, 4x6, 6x9) = 1.5
- 7x11 = 1.571
- 5x8 (10x16) = 1.6
- 3x5 (12x20) = 1.667
- 8.5x15 = 1.765
- 8x16 = 2
- 9x21 = 2.334 (wrong in Ansel preset)
- 5x12 = 2.4
- 7x17 = 2.428
- 2x5 (4x10, 8x20) = 2.5
- 24x65 (Xpan) = 2.708

**Comment by pjhyor7** [comment]
Would it not be a good idea to be able to input your own custom ratio?

**Comment by aurelienpierre** [comment]
> Would it not be a good idea to be able to input your own custom ratio?

It has been possible to do so since forever.
