### ISSUE TITLE
Program crashed after changing orientation of cropping and clicking "Apply"

### ISSUE THREAD

**Issue by AlynxZhou** [aurelienpierreeng/ansel#275]
## Description of the bug

Just like the title.

**To Reproduce**

1. Go to darkroom.
2. Click on crop module.
3. Click "Edit".
4. Click the arrow button next to ratio to change orientation.
5. Click "Apply"

## Expected behavior

Photo is cropped.

## Context

**Screenshots**

**Screencast**

This is the CLI output, it looks like some thread locks error:

[ansel-crop-crash.txt](https://github.com/aurelienpierreeng/ansel/files/13687126/ansel-crop-crash.txt)

The program says it writes backtrace to `/tmp`, but the file is empty, so I assume if I start it from CLI it will just output to terminal.

## Which commit introduced the error

I am using <https://github.com/aurelienpierreeng/ansel/commit/0a2bf45eff53d73e489e4fdd389812d413e3efc2>.

The last commit I tried without this issue (but the crop orientation still doesn't work correctly) is <https://github.com/aurelienpierreeng/ansel/commit/3cf785d378a9404ca894691dd79a96030eec267f>.

## System

* darktable version : 0.0.0.r640.g0a2bf45ef
* OS                : Linux 6.6.6
* Linux - Distro    : Arch Linux
* Memory            : 32G
* Graphics card     : RTX2070S
* Graphics driver   : nvidia
* OpenCL installed  : Y
* OpenCL activated  : Y
* Xorg              : Wayland
* Desktop           : GNOME
* GTK+              : 3.24.38
* gcc               : 13.2.1
* cflags            : `-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection`
* CMAKE_BUILD_TYPE  : Release

**Additional context**

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**
 - Do you use lua scripts?
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by AlynxZhou** [comment]
[ansel-crop-crash-debug.txt](https://github.com/aurelienpierreeng/ansel/files/13687296/ansel-crop-crash-debug.txt)

I get GDB output of a debug build. Not sure why backtrace is not written to the backtrace file in `/tmp` for me, but that's not important.

**Comment by aurelienpierre** [comment]
Fixed by [53c609c](https://github.com/aurelienpierreeng/ansel/commit/53c609cd274b6b893ed10214ac6877941d1b486b)

**Comment by AlynxZhou** [comment]
Thanks!
