### ISSUE TITLE
The Appimage has stopped working

### ISSUE THREAD

**Issue by Annabel2** [aurelienpierreeng/ansel#276]
I've been using the Ansel Appimage for a while with Ubuntu 20.04.  Currently appimage Ansel-06d9cda-x86_64 from about a month ago.  This is still working.
Today I downloaded the latest, Ansel-3cf785d-x86_64, but it won't run.  I've set it to allow execution in Permissions.  When I double-click it, nothing happens.  I downloaded an older one, several days old, that was the same.  If I re-download my current one, 06d9cda, that works.
Any ideas please?!

**Comment by TimConnelly** [comment]
I just hit the same issue on Ubuntu 20.04. It appears that Ansel-3cf785d-x86_64 relies on a minimum glibC version of 2.32, whereas Ubuntu 20.04 ships 2.31. Without tracking down the reason for the change, the options I see are:
1. Use older build
2. Build latest locally
3. Upgrade to Ubuntu 22.04, which uses a newer glibC (I intend to do this soon anyway)

**Comment by aurelienpierre** [comment]
My hands are tied here. Rawspeed needs at least GCC 12, which is not available on Ubuntu 20.04.

**Comment by Annabel2** [comment]
I understand these things to only a limited degree but I thought the whole point of appimages, flatpaks, was to avoid version clashes and build problems.  I.e. appimage has GCC12 within it.

**Comment by Tokariew** [comment]
The problem with flatpak is it not supporting opencl for AMD cards currently.
