### ISSUE TITLE
Bug in check-boxes in 'Open from disk...' window

### ISSUE THREAD

**Issue by LucaZulberti** [aurelienpierreeng/ansel#278]
## Description of the bug

In 'Open from disk...' modal, with english UI there are three check-box without labels, with Italian translation some internals appears.

**To Reproduce**

1. Click on 'Open from disk...'

## Expected behavior

Idk

## Context

**Screenshots**
English:
![immagine](https://github.com/aurelienpierreeng/ansel/assets/8284106/cf5aee02-3f97-4afe-94fe-87dbe2119f18)

Italian:
![immagine](https://github.com/aurelienpierreeng/ansel/assets/8284106/2622a8ad-009f-44df-895b-db67107d624e)

## System

* darktable version : 0.0.0+627~g702c4c5f0
* OS                : Linux - kernel 6.2.0-39
* Linux - Distro    : Ubuntu 22.4

**Comment by Jiyone** [comment]
I think you are using an old commit 🤔

**Comment by pedrorrodriguez** [comment]
I think so too. Try using the latest app image

**Comment by LucaZulberti** [comment]
No I compiled with latest commit on master (I did it again now after a clean of the build directory to be sure): 0.0.0+627~g702c4c5f0

**Comment by LucaZulberti** [comment]
I confirm that in the AppImage the UI is different and the import from File-> is working

**Comment by LucaZulberti** [comment]
Ok, my fault, I don't know after the pull and the clean of the directory it wasn't upgraded.. Next time I will check it once more than twice.
