### ISSUE TITLE
"Styles" panel disappeared

### ISSUE THREAD

**Issue by GuidoGonzato** [aurelienpierreeng/ansel#279]
## Description of the bug

Releases equal to or newer than 702c4c5 make the Style panel disappear, and there's apparently no way to get the Styles back.
I "solved" by rolling back to release Ansel f7669af, which is the last release unaffected from another bug I'll report (Ctrl + mouse and Shift + mouse not working). I also had to remove $HOME/.config/ansel. *Very* bad bug. Good thing I had a backup of my styles.

**To Reproduce**

Start Ansel 702c4c5 or newer; the Style panel is gone.

## Expected behavior

The Style panel should not vanish.

## Context

**Screenshots**

**Screencast**

## Which commit introduced the error

Apparently, Ansel 702c4c5 

## System

* darktable version : 702c4c5 
* OS                : Linux 5.15.0-89-generic
* Linux - Distro    : Linux Mint 21.2 (VIctoria)
* Memory            : 8GB
* Graphics card     :  NVIDIA GeForce 920M
* Graphics driver   : nvidia-driver-470
* OpenCL installed  : unknown
* OpenCL activated  : unknown
* Xorg              : 1:7.7+23ubuntu2
* Desktop           : Mate
* GTK+              : unknown
* gcc               : unknown
* cflags            : unknown
* CMAKE_BUILD_TYPE  : unknown
![Ansel 702c4c5 - BUG](https://github.com/aurelienpierreeng/ansel/assets/40196608/b4d39ac5-e1ac-4f3b-b7d1-0b060859f4f2)
![Ansel f7669af OK](https://github.com/aurelienpierreeng/ansel/assets/40196608/5a6b7982-9938-4999-8186-1c6fff124018)

**Additional context**

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**
 - Do you use lua scripts?
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by aurelienpierre** [comment]
Styles are temporarily unavailble until the history read-write is made thread-safe. They will re-appear in global menu.

**Comment by GuidoGonzato** [comment]
Fine, thanks.

**Comment by aurelienpierre** [comment]
Part of #262. Closing here.
