### ISSUE TITLE
Ctrl + mouse, Shift + mouse not working

### ISSUE THREAD

**Issue by GuidoGonzato** [aurelienpierreeng/ansel#280]
## Description of the bug

Ctrl + mouse and Shift + mouse, used to modify values in sliders by small or large amount, don't work since release 57ed58d. Hence, it's impossible to specify exact values in, say, watermark positions.

**To Reproduce**

Start Ansel 57ed58d or newer, then try to use Ctrl + mouse or Shift + mouse in any slider.

## Expected behavior

Ctrl + mouse should modify slider values by small amounts, while Shift + mouse by large amounts. As per documentation.

## Context

**Screenshots**

**Screencast**

## Which commit introduced the error

Ansel 57ed58d

## System

* darktable version : https://github.com/aurelienpierreeng/ansel/commit/702c4c5f0a84f1972b9bf0d90a6250d6850545fe
* OS : Linux 5.15.0-89-generic
* Linux - Distro : Linux Mint 21.2 (VIctoria)
* Memory : 8GB
* Graphics card : NVIDIA GeForce 920M
* Graphics driver : nvidia-driver-470
* OpenCL installed : unknown
* OpenCL activated : unknown
* Xorg : 1:7.7+23ubuntu2
* Desktop : Mate
* GTK+ : unknown
* gcc : unknown
* cflags : unknown
* CMAKE_BUILD_TYPE : unknown

**Additional context**

 - Can you reproduce with another darktable version(s)? **yes with all versions newer than 57ed58d
 - Can you reproduce with a RAW or Jpeg or both? both
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? yes
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? yes
 - Do you use lua scripts? no
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by Jiyone** [comment]
I think it's made on purpose

**Comment by aurelienpierre** [comment]
If by "Ctrl+mouse" you mean Ctrl+mouse wheel, it works here. Shift+scroll too. The difference is you have to capture the scrolling focus by clicking the slider first (or its label).

**Comment by GuidoGonzato** [comment]
I confirm that it works. I missed the change from Ctrl + mouse click and movement to Ctrl + mouse wheel. Thanks.
