### ISSUE TITLE
To reset eyedropper's frame is not saved 

### ISSUE THREAD

**Issue by Jiyone** [aurelienpierreeng/ansel#287]
## Description of the bug

The eyedropper frame size and position is not "saved" when the last action before switching OFF the eyedropper view was to reset its frame to full size using right-click.

Also, the pipe doesn't recompute after resetting an eyedropper frame, I believe this would be related.

**To Reproduce**

1. Click on an eyedropper button.
2. Draw a zone in the picture.
3. Right-click on the eyedropper's frame to reset, the selection is now on all the picture.
    (side effect : the pipeline doesn't recompute)
5. Switch the eyedropper button OFF, the zone delimitation disappears.
6. Switch the eyedropper button ON.
7. See the zone delimitation is now the same as after step 2.

## Expected behavior

The pipe should recompute after an eyedropper's frame reset.
The size and position of the frame should be recorded when the button switched OFF and reloaded later.

## System

* Ansel version : at least 9beb399
* OS                : Win11 22H2

**Comment by rprego** [comment]
I'm seeing similar behavior in ba4dc39 on Linux. Clicking an eyedropper button briefly shows a zone frame, but then the frame quickly disappears.

**Comment by aurelienpierre** [comment]
That should be fixed now ?

**Comment by Jiyone** [comment]
yep thanks
