### ISSUE TITLE
Import adds an invalid empty folder

### ISSUE THREAD

**Issue by vtyrtov** [aurelienpierreeng/ansel#291]
## Description of the bug

When you request an import File > Import ("Copy to disk"), an empty folder is created with the current date and the previous "Project name"

**To Reproduce**

1. Go to "File > Import"
2. Select location 
4. Click on any file
5.  See import folder - an empty folder has been created 

## Expected behavior

The folder should be created after clicking the Import button

**Screenshots**

![image](https://github.com/aurelienpierreeng/ansel/assets/22073549/889cb1cd-5991-4489-a31c-f6430fea3a62)

## System

* Ansel version : 5b98f93
* OS : linux 6.6.6-200.fc39.x86_64
* Linux - Distro : Fedora Linux 39 (Workstation Edition)

**Comment by aurelienpierre** [comment]
WIP in #294

**Comment by lukadh** [comment]
any news on this? 

![image](https://github.com/aurelienpierreeng/ansel/assets/64734384/c17ee772-a190-47f4-b330-4bfd40ebcf26)

**Comment by Jiyone** [comment]
fixed in #294
