### ISSUE TITLE
Rotate and Perspective module background problem

### ISSUE THREAD

**Issue by audiomartin** [aurelienpierreeng/ansel#292]
## Description of the bug

While working with Rotate and Perspective module in Ansel Version ca-74e8a (Win10, i7-2600, Geforce GTX 1050ti) there happened some strange behavior to the background in Darkroom Atelier. See Screenshot:

![Clipboard01_Rotate](https://github.com/aurelienpierreeng/ansel/assets/43499366/c30c3834-a8a3-44b7-b60e-baa798d8d156)

Aswell the Mouse Pointer is misaligned, i am not able to grab the handle. See:

![Clipboard02_Rotate](https://github.com/aurelienpierreeng/ansel/assets/43499366/ba041d20-56d7-4558-8e44-c51987f952a7)

AtB
martin

**Comment by audiomartin** [comment]
Working now with Version a23b63a-win-exe.

Merry X-mas

**Comment by aurelienpierre** [comment]
Happy new year !
