### ISSUE TITLE
UI Scopes module

### ISSUE THREAD

**Issue by audiomartin** [aurelienpierreeng/ansel#293]
Since some versions the Scopes module  is in the left panel under the Preview/NAvigation Module.  I would like to see the Scopes Module to come back on the right top corner. I like to see the Scopes on top of the adjusting modules to have a visual control closer to the handles/numbers i am changing.

AtB
martin

**Comment by pedrorrodriguez** [comment]
Scopes eventually will become a module in the pipeline.

**Comment by AlynxZhou** [comment]
> Scopes eventually will become a module in the pipeline.

Really? I think it should be easier to access at a fixed place. And it doesn't affect output result, pipeline is about computing the result, right?

**Comment by pedrorrodriguez** [comment]
Bringing it into the pipeline as a module will allow to sample values at any point in the pipeline.

**Comment by aurelienpierre** [comment]
Scopes will be merged with color picker, since they interact with each other anyway, and will stay on the left sideba. Right sidebar will be dedicated to pixel filters and use the whole vertical real-estate for long modules, left sidebar to utils
