### ISSUE TITLE
Zooming messes with pipeline (preview in Darkroom not stable)

### ISSUE THREAD

**Issue by LucaZulberti** [aurelienpierreeng/ansel#296]
## Description of the bug

When I zoom while in Darkroom, the processing of highlights changes.

**To Reproduce**

1. Click on an image to open 'Darkroom'
2. Apply some modification with Tones
3. Zoom in and zoom out to see different results
4. Can happen also to see artifacts while moving in zoomed view: ![Image](https://github.com/aurelienpierreeng/ansel/assets/8284106/39110241-b27a-4daf-908d-4a926eff7c34)

## Expected behavior

Results zoomed in/out without change colors/light result.

## Context

**Screenshots**

Before
![Before](https://github.com/aurelienpierreeng/ansel/assets/8284106/9d269164-c240-4d6e-aba0-d0aa7824e424)

After
![After](https://github.com/aurelienpierreeng/ansel/assets/8284106/7dd88535-5f1d-49c0-84c2-67e8550bb759)

## UPDATE - Which commit introduced the error

After bisecting, the bug seems to be introduced at:
```
ba4dc399ea51bebb4cfeda2e081e981557cdf175 is the first bad commit
commit ba4dc399ea51bebb4cfeda2e081e981557cdf175
Author: Aurélien PIERRE <aurelien@aurelienpierre.com>
Date:   Wed Dec 20 21:56:43 2023 +0100

    Pixelpipe cache: ensure the cache is used from the first run

 src/develop/develop.c      |  4 ++--
 src/develop/develop.h      |  5 -----
 src/develop/pixelpipe_hb.c | 17 ++++++-----------
 3 files changed, 8 insertions(+), 18 deletions(-)
```

Anyway, also at the commit 43696fb645bc34c9c20a3cbc942b2af3e6cee727, sometime I experienced the artifacts produced while moving in zoomed view. No change of light, and not always.

## UPDATE - System
Linux 6.2.0-39-generic #40~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC

ansel --version
this is ansel 0.0.0+659~gba4dc399e
copyright (c) 2009-2023 johannes hanika
https://github.com/aurelienpierreeng/ansel/issues

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 8.0.0
  Colord support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled

**Additional context**

 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? yes

**Comment by LucaZulberti** [comment]
Hi @aurelienpierre, I did the bisect and updated the description.

**Comment by aurelienpierre** [comment]
Thanks ! I have a possible solution for that.

**Comment by AlynxZhou** [comment]
I can also reproduce this.

**Comment by svillar** [comment]
I've just reproduced it too

**Comment by aurelienpierre** [comment]
Should be fixed now. Re-open if not.
