### ISSUE TITLE
Build fails due to recent translation changes

### ISSUE THREAD

**Issue by cycomanic** [aurelienpierreeng/ansel#304]
## Description of the bug

Latest git checkout fails to build with a translation error in it.po

[10/898] Building it locale
FAILED: po/it/LC_MESSAGES/ansel.mo /home/jschrod/Downloads/Photo/ansel/build/po/it/LC_MESSAGES/ansel.mo 
cd /home/jschrod/Downloads/Photo/ansel/build/po && /usr/bin/msgfmt -v -c /home/jschrod/Downloads/Photo/ansel/po/it.po -o /home/jschrod/Downloads/Photo/ansel/build/po/it/LC_MESSAGES/ansel.mo
/home/jschrod/Downloads/Photo/ansel/po/it.po:4315: 'msgid' and 'msgstr' entries do not both end with '\n'

**To Reproduce**

1. Checkout latest git
2. sh build.sh 

## Expected behavior

build should succeed

## Which commit introduced the error

fe9d009

**Comment by hgmarty** [comment]
Fix with PR #305 
To compile : edit po/it.po, add "\n" in the end of line 4317
