### ISSUE TITLE
Image disorted when changing TCA overwrite. Fixes when zooming.

### ISSUE THREAD

**Issue by pjhyor7** [aurelienpierreeng/ansel#306]
## Description of the bug

When changing the value of TCA Overwrite, the main preview image is heavily distorted. This is fixed when zooming in or out. 

**To Reproduce**

1. Open image in Darkroom
2. Enable Lens Correction
3. Enable TCA Overwrite in Lens Correction
4. Change value of TCA Red or TCA Blue
5. See distorted main preview image.
6. Zoom in or out of main image to see fix.

## Expected behavior

TCA applied without the heavily distortion

**Screenshots**

![Screenshot 2024-01-01 193151](https://github.com/aurelienpierreeng/ansel/assets/36453655/2bc2cce1-ea54-43a8-bef3-c245b9139e49)

## Which commit introduced the error

f4d6756

## System

Darktable version: f4d6756
OS : Windows 10 (build 19045)
Memory : 24576mb
Graphics card : AMD Radeon R9 200
OpenCL installed : Yes
OpenCL activated : Yes

**Comment by aurelienpierre** [comment]
Should be fixed now, it was linked to pipeline cache invalidation issues now solved.
