### ISSUE TITLE
Window Maximize (Repeat Issue)

### ISSUE THREAD

**Issue by davidvj** [aurelienpierreeng/ansel#31]
I previously reported that I was having problems with the Maximize window setting when in the darkroom mode. I thought that the problem was solved when I changes a setting for font scaling in my settings manager. However the problem has surfaced once again and following system and program upgrades it is now apparently worse.
The lighttable window is fine .... I can maximize/minimize and scale the window in both directions. The problem is only seen in the darkroom window.
In the darkroom window maximize simply does not work and the window fails to scale in the vertical direction so that 1/4 of the screen is not available.
I am running R&D on an older laptop (Lenovo W530) with Manjaro/Arch/XFCE ..... nothing fancy.
As a test this morning I switched over to the regular dt to try and determine if this was a system related situation .... regular dt functions correctly.

**Comment by aurelienpierre** [comment]
I may have removed a layer of paint that held the rust in the darkroom…

**Comment by aurelienpierre** [comment]
I guess that should be fixed now

**Comment by aurelienpierre** [comment]
Reopen if that problem still exists.
