### ISSUE TITLE
masks: hiding the mask view randomly causes a black or disturbed central view.

### ISSUE THREAD

**Issue by blonchkman** [aurelienpierreeng/ansel#312]
## Description of the bug

Hiding the mask view after a movement of the detail threshold randomly causes a black or disturbed central view.
This behavior happens to me one or two times out of 10 when I remove the mask view after moving the detail slider.

**To Reproduce**

Preparation:
- create a new Color Calibration instance
- create a parametric mask on this instance

Reproduction:
1. Activate mask view (single-click on button)
1. Change detail threshold, left or right
1. Deactivate mask view (single-click on button)
1. Repeat step 1 until perturbation at step 3.

## Expected behavior

Return to current central view.

## Context

**Screenshots**
![Screenshot_20240104_191749](https://github.com/aurelienpierreeng/ansel/assets/9490397/67ead513-0783-400f-8032-acb3811ab3e0)
![Screenshot_20240104_191445](https://github.com/aurelienpierreeng/ansel/assets/9490397/8ef906f7-8c0a-48be-ac21-8ab0cfff3cb3)

## System

Ansel, commit 8801a4d
Ubuntu linux 22.04

**Additional context**
- The random erratic behavior of the central view is not linked to the detail threshold. 
- Another person acting on the G and Jz parameter sliders confirms a disturbed central view after 20 attempts, but no black occurrences.
- I've noticed one disturbed central view on 50 tests and 1 or 2 black occurrences on 10 tests.
- I still have to check whether color calibration is the only module affected.

**Comment by aurelienpierre** [comment]
Details masks are a terrible hack meant to alleviate the detrimental side-effects of sharpening algorithms by allowing to exclude "edges" :

- they are computed in the demosaicing module at full resolution (in any case, at higher resolution than preview buffer),
- they need to pass through several geometric distortions, inducing errors,
- they need to be downsampled for the module using them, inducing errors,
- their darkroom preview is heavily zoom-dependent, to the point where their effect might be completely invisible when zoomed out.

It's a brittle design that can't be fixed, to solve a problem that should be fixed within sharpening algorithms (diffuse & sharpen uses a variance-based edge detection to regularize the effect near sharp edges).

The details mask will be deprecated.

**Comment by aurelienpierre** [comment]
Should be fixed now.
