### ISSUE TITLE
Feature request: User-defined module groups

### ISSUE THREAD

**Issue by rprego** [aurelienpierreeng/ansel#315]
The ability to create a user-defined module group in Darktable was something I found very useful there. It seems like that feature was removed in Ansel. Is there a possibility for continuing to include the ability to have a user-defined module list for modules that someone uses in processing most of their images?

**Comment by aurelienpierre** [comment]
No, modules groups are organized workflow-wise and pipeline-wise to guide the workflow into the 86 modules we have. What Darktable does is only giving users a wrong idea that workflow is a personal choice that consists in arranging GUI widgets in a pretty way, while it's arranging layer in a vertical stacks where order matters.
