### ISSUE TITLE
Mouse pan/zoom leaks GPU memory in Darkroom

### ISSUE THREAD

**Issue by tajuma** [aurelienpierreeng/ansel#317]
## Description of the bug

OpenCL gets disabled after a few mouse wheel pan/zoom in Darkroom.

**To Reproduce**

1. Open a raw image (without any modules other than the default pipeline) in Darkroom view.
2. Start monitoring GPU memory usage, e.g. with nVidia cards use `nvidia-smi -l`.
3. Mouse wheel zoom to 100% level in the picture.
4. Mouse wheel zoom back to original zoom level (fit the screen).
5. Pan picture (even if the picture fits the screen i.e. will not actually move).
6. Repeat steps 3 and 5 and notice GPU memory growing. 
7. Depending on your GPU memory size, ansel will eventually disable OpenCL with message 

_ansel discovered problems with your OpenCL setup; disabling OpenCL for this session!_
  
The only way to free GPU memory is to exit ansel, e.g. closing Darkroom does not free the GPU memory.

On my setup I see a single mouse wheel zoom to take a few 100MB GPU memory and long pan (e.g. whole screen width) upto 3GB in one go.

## Expected behavior

OpenCL will not get disabled and GPU memory consumption would not grow.

## Context

When OpenCL gets disabled `ansel-cltest` shows out of GPU memory error

```
% clinfo -l
Platform #0: NVIDIA CUDA
 `-- Device #0: NVIDIA GeForce RTX 3050 6GB Laptop GPU

% ./root/opt/ansel/bin/ansel-cltest
[dt_get_sysresource_level] switched to 1 as `default'
  total mem:       64031MB
  mipmap cache:    8003MB
  available mem:   32015MB
  singlebuff:      500MB
  OpenCL tune mem: OFF
  OpenCL pinned:   OFF
[opencl_init] opencl related configuration options:
[opencl_init] opencl: ON
[opencl_init] opencl_scheduling_profile: 'default'
[opencl_init] opencl_library: 'default path'
[opencl_init] opencl_device_priority: '*/!0,*/*/*'
[opencl_init] opencl_mandatory_timeout: 400
[opencl_init] opencl_synch_cache: active module
[opencl_init] opencl library 'libOpenCL' found on your system and loaded
[opencl_init] found 1 platform
[opencl_init] found 1 device

[dt_opencl_device_init]
   DEVICE:                   0: 'NVIDIA GeForce RTX 3050 6GB Laptop GPU'
   CANONICAL NAME:           nvidiageforcertx30506gblaptopgpu
   PLATFORM NAME & VENDOR:   NVIDIA CUDA, NVIDIA Corporation
   DRIVER VERSION:           535.113.01
   DEVICE VERSION:           OpenCL 3.0 CUDA, SM_20 SUPPORT
   DEVICE_TYPE:              GPU
   GLOBAL MEM SIZE:          5938 MB
   MAX MEM ALLOC:            1484 MB
   MAX IMAGE SIZE:           32768 x 32768
   MAX WORK GROUP SIZE:      1024
   MAX WORK ITEM DIMENSIONS: 3
   MAX WORK ITEM SIZES:      [ 1024 1024 64 ]
   ASYNC PIXELPIPE:          NO
   PINNED MEMORY TRANSFER:   NO
   MEMORY TUNING:            NO
   FORCED HEADROOM:          400
   AVOID ATOMICS:            NO
   MICRO NAP:                250
   ROUNDUP WIDTH:            16
   ROUNDUP HEIGHT:           16
   CHECK EVENT HANDLES:      128
   PERFORMANCE:              0.896092
   DEFAULT DEVICE:           NO
   *** could not create context *** CL_OUT_OF_HOST_MEMORY
[opencl_init] no suitable devices found.
[opencl_init] FINALLY: opencl is NOT AVAILABLE on this system.
[opencl_init] initial status of opencl enabled flag is OFF.
```

Same kind of GPU memory consumption happens with OpenCL on integrated Intel GPU. I don't know any good tool to measure Intel GPU memory consumption, but xorg kept growing (system memory usage went from 5GB to 45 GB with a dozen or so zoom/pan operations) and went back to normal only when ansel exited

```
% clinfo -l
Platform #0: Intel(R) OpenCL Graphics
 `-- Device #0: Intel(R) Iris(R) Xe Graphics

% ./root/opt/ansel/bin/ansel-cltest
[dt_get_sysresource_level] switched to 1 as `default'
  total mem:       64031MB
  mipmap cache:    8003MB
  available mem:   32015MB
  singlebuff:      500MB
  OpenCL tune mem: OFF
  OpenCL pinned:   OFF
[opencl_init] opencl related configuration options:
[opencl_init] opencl: ON
[opencl_init] opencl_scheduling_profile: 'default'
[opencl_init] opencl_library: 'default path'
[opencl_init] opencl_device_priority: '*/!0,*/*/*'
[opencl_init] opencl_mandatory_timeout: 400
[opencl_init] opencl_synch_cache: active module
[opencl_init] opencl library 'libOpenCL' found on your system and loaded
[opencl_init] found 1 platform
[opencl_init] found 1 device

[dt_opencl_device_init]
   DEVICE:                   0: 'Intel(R) Iris(R) Xe Graphics'
   CANONICAL NAME:           intelririsrxegraphics
   PLATFORM NAME & VENDOR:   Intel(R) OpenCL Graphics, Intel(R) Corporation
   DRIVER VERSION:           23.39.27427.23
   DEVICE VERSION:           OpenCL 3.0 NEO
   DEVICE_TYPE:              GPU
   GLOBAL MEM SIZE:          51225 MB
   MAX MEM ALLOC:            4096 MB
   MAX IMAGE SIZE:           16384 x 16384
   MAX WORK GROUP SIZE:      512
   MAX WORK ITEM DIMENSIONS: 3
   MAX WORK ITEM SIZES:      [ 512 512 512 ]
   ASYNC PIXELPIPE:          NO
   PINNED MEMORY TRANSFER:   NO
   MEMORY TUNING:            NO
   FORCED HEADROOM:          400
   AVOID ATOMICS:            NO
   MICRO NAP:                250
   ROUNDUP WIDTH:            16
   ROUNDUP HEIGHT:           16
   CHECK EVENT HANDLES:      128
   PERFORMANCE:              0.634240
   DEFAULT DEVICE:           NO
   KERNEL DIRECTORY:         root/opt/ansel/share/ansel/kernels
   CL COMPILER OPTION:       -cl-fast-relaxed-math
   KERNEL LOADING TIME:       0.0106 sec
[opencl_init] OpenCL successfully initialized.
[opencl_init] here are the internal numbers and names of OpenCL devices available to darktable:
[opencl_init]           0       'Intel(R) Iris(R) Xe Graphics'
[opencl_init] FINALLY: opencl is AVAILABLE on this system.
[opencl_init] initial status of opencl enabled flag is ON.
[dt_opencl_update_priorities] these are your device priorities:
[dt_opencl_update_priorities]           image   preview export  thumbs
[dt_opencl_update_priorities]           0       -1      0       0
[dt_opencl_update_priorities] show if opencl use is mandatory for a given pixelpipe:
[dt_opencl_update_priorities]           image   preview export  thumbs
[dt_opencl_update_priorities]           0       0       0       0
[opencl_synchronization_timeout] synchronization timeout set to 200
```

## Which commit introduced the error

`e2c4a0a60`

## System

* ansel version :  e2c4a0a60 2024-01-05T15:37:55+01:00 Fixed error and improved some strings
* OS                :  Linux - kernel 6.5.0
* Linux - Distro    : Tuxedo 22.04 (~= Ubuntu 22.04)
* Memory            : 64GB
* Graphics card     :  NVIDIA GeForce RTX 3050 6GB Laptop GPU + Intel(R) Iris(R) Xe Graphics
* Graphics driver   : OpenCL 3.0 CUDA, 535.113.01 + OpenCL 3.0 NEO, 23.39.27427.23
* OpenCL installed  : yes
* OpenCL activated  : yes
* Xorg              : 7.7+23ubuntu2
* Desktop           :  KDE Plasma Version: 5.27.8
* GTK+              : 3.24.33-1ubuntu2
* gcc               : gcc version 12.3.0 (Ubuntu 12.3.0-1ubuntu1~22.04)
* cflags            : defaults
* CMAKE_BUILD_TYPE  : Release

**Additional context**

Intel OpenCL stack is from 

https://github.com/intel/compute-runtime/releases/tag/23.39.27427.23 and https://github.com/intel/intel-graphics-compiler/releases/tag/igc-1.0.15136.22

**Comment by tajuma** [comment]
This issue seems to be due to restarting pixel pipeline and not releasing `cl_mem_output` buffer if restart is requested (e.g. due to two zoom-in commands in rapid succession). Adding a conditional release for it in the two KILL_SWITCH macros seems to fix the issue. With this applied my GPU memory usage is stabilized.

I will create a pull request for this...

**Comment by aurelienpierre** [comment]
Fixed
