### ISSUE TITLE
CLI/Parallel processing

### ISSUE THREAD

**Issue by webysther** [aurelienpierreeng/ansel#323]
**What is the current problem you are facing ?**
I started moving from LrC to darktable and got some problems when trying to ask for help to improve the software, after few rounds I start search again and find the project, I will list here the issues and trying to summarise what I want to do:

- darktable-org/darktable/issues/16252
- darktable-org/darktable/issues/16253
- darktable-org/darktable/issues/16255

**Where in your workflow does your problem occur ?**
I want to automate the ingestion process using more headless or paralel as possible, for me transform everything into cli as possible make possible to create some automations and if possible to run in another machine some will be better, this is why I open 3 issues on darktable, to be able to automate you need to have cli, to use the cli with gui, will need parallel, if you need to have a smooth/fast operation you need to divide to conquer.

**Additional context**
Please if you want help or have a better tool, I don't want to use another tools because compat problems that can be happen because of how everyone write to XMP.

If you need help in some way or have some advice or expand the discussion.

**Comment by aurelienpierre** [comment]
What is the end goal of automation here ?

That's not possible as of now, because Ansel relies on a SQLite database that can't be accessed concurrently from different processes while preventing data corruption. Plus a good deal of presets and default settings is done in GUI code. CLI usage is only meant to batch-process pictures that have already been edited.

**Comment by aurelienpierre** [comment]
Building the thumb cache has already a CLI command for the whole DB and a GUI control from global menu. As for local copies, I don't know. But for both, parallel processing is not needed.

**Comment by webysther** [comment]
> Building the thumb cache has already a CLI command for the whole DB and a GUI control from global menu. As for local copies, I don't know. But for both, parallel processing is not needed.

thanks!
