### ISSUE TITLE
Image processing and UI performance regressions

### ISSUE THREAD

**Issue by MC-DeltaT** [aurelienpierreeng/ansel#325]
## Description of the bug

This is a somewhat vague issue, not sure if it is a bug per-se, but I thought it may be worth discussing anyway.

Recently I upgraded from commit 1d3f83d to the latest release (which I think is ba4dc3), and have noticed a lot slower image processing and UI response. I haven't pinned down any particular module which is slow, it seems to be a general slowdown across many aspects of the editing workflow. My PC hardware, OS, and input images haven't changed so I would guess it has been some change to Ansel since a few months ago.

Some things I have noticed:

- The UI often freezes for several seconds upon changing module parameters, even before the "working" prompt comes up (which I assume indicates the image pipeline processing).
- Sometimes it seems like the image is reprocessing for no reason ("working" prompt is shown), like clicking on a module to expand it or changing tabs in module UIs.
- General flakiness of image processing w.r.t. UI updates, e.g.:
  - Colour picker doesn't always update when selecting a point on the image.
  - Scopes don't always update.
  - Occasionally changing parameters or toggling a module on/off doesn't update the image.
- When changing multiple module parameter in quick succession, seems like the image pipeline runs for each change, leading to long delays.
- The image processing and UI performance issues get worse with more modules active (makes sense).

By the end of editing one image, the UI feels almost unusably slow. Often waiting several seconds after any UI interaction, whereas previously everything felt pretty snappy.

I don't know what's changed in the backend with Ansel recently, but I wonder if there has been any big changes to how UI events are handled and when we decide to rerun the image pipeline.

**To Reproduce**

Do any kind of regular image editing in Darkroom, e.g. exposure, filmic RGB, colour calibration, colour balance, local contrast. By the end the performance issues are apparent to me, as described above.

## Expected behavior

Not expecting the performance to change so significantly given that there haven't been massive changes to the image processing features I use in my editing. My PC is not the most powerful but I was quite happy with Ansel's performance previously.

## System

darktable version : unknown - whichever came with the Ansel install
OS : Win10, version 22H2, build 19045.3930
Memory : 8GB, 2133 MHz
Graphics card : Nvidia GeForce 920MX
Graphics driver : GeForce game ready driver version 537.42
OpenCL installed : unknown
OpenCL activated : No
GTK+ : unknown
gcc : unknown
cflags : unknown
CMAKE_BUILD_TYPE : unknown

**Additional context**

- Are the steps above reproducible with a fresh edit (i.e. after discarding history)? Yes
- Do you use lua scripts? No

**Comment by aurelienpierre** [comment]
There is nothing specific nor useful in this issue.

**Comment by MC-DeltaT** [comment]
> There is nothing specific nor useful in this issue.

Please let me know how I may better/properly report this significant usability regression.

**Comment by aurelienpierre** [comment]
I have updated the bug report form, you can try again.
