### ISSUE TITLE
Actions issue: Releases are broken

### ISSUE THREAD

**Issue by cricalix** [aurelienpierreeng/ansel#332]
### Code of Conduct

- [X] I have read this document and I accept the conditions

### Search previous report

- [X] I have searched my issue

### Computer's operating system

Linux

### What GPU do you have ?

AMD/ATI

### Ansel version

N/A

### Type of binary

Pre-built packages provided by the Ansel project (.AppImage, .EXE)

### What happened?

The actions pipeline for releases is red for all nightlies as far as I can see. There are warnings about one of the dependencies being deprecated, but unfortunately the actual errors are only visible to the pipeline/repository owner.

The impact of this is that the AppImage nightly download link on ansel.photos doesn't work, because no release has been generated recently (it implies a 90 day cache).

### Does your problem occur with OpenCL enabled ?

No

### Does your problem occur with OpenCL disabled ?

No

**Comment by aurelienpierre** [comment]
libcurl was updated from 7.8 to 8.8 on Windows MSYS2 and that version is bugged, breaking CI and nightly builds.

**Comment by aurelienpierre** [comment]
Fixed

**Comment by cricalix** [comment]
Thank you.
