### ISSUE TITLE
Bug: Copying settings from grouped image does not work when group is closed

### ISSUE THREAD

**Issue by brownphotographic** [aurelienpierreeng/ansel#333]
### Code of Conduct

- [X] I have read this document and I accept the conditions

### Search previous report

- [X] I have searched my issue

### Computer's operating system

Linux

### What GPU do you have ?

Nvidia

### Ansel version

0.0.0+748~g61eb388

### Type of binary

Pre-built packages provided by the Ansel project (.AppImage, .EXE)

### What happened?

When I try to copy settings from an image in a group, if the group is closed I get an error on the screen:

"Copy is allowed only with exactly one image selected"

For example, if I have a RAW and JPEG in a group, by default the group is closed. I would like to be able to be able to copy and paste settings from one of the RAWs (on top of the group stack) to the other adjacent images. 

Expected behavior: the image that is represented in the group should be the 'one' image that is selected. 

Thank you

### Does your problem occur with OpenCL enabled ?

Yes

### Does your problem occur with OpenCL disabled ?

I don't know

**Comment by aurelienpierre** [comment]
This is not a bug, as the label suggests : copying an history to a group of images is ambiguous (should we copy on the first or an all ?) and may result in data losses if it was a mistake. You are expected to ungroup pictures first (shortcut : Ctrl+G if I recall correctly), and explicitly select all target pictures. It takes a bit more steps but prevents many mistakes.
