### ISSUE TITLE
Bug: Crash when copying file in import for the first time

### ISSUE THREAD

**Issue by nortio** [aurelienpierreeng/ansel#345]
### Code of Conduct

- [X] I have read this document and I accept the conditions

### Search previous report

- [X] I have searched my issue

### Computer's operating system

Linux

### What GPU do you have ?

I don't know

### Ansel version

g76a90ce

### Type of binary

Pre-built packages provided by the Ansel project (.AppImage, .EXE)

### What happened?

When opening Ansel for the first time, if you first try to select a photo, then select "Copy to disk", Ansel crashes. This also happens if you select "Copy to disk" first and then highlight a file. This only happens on a fresh start (tested by removing `.config/ansel`). 
It specifically fails on `path lookup '<ansel appimage path>/ansel.stable.AppImage/2024-06-22-xxxxx' fails with: 'No such file or directory'`. I believe this happens because there is no default "Base directory" (at least on my setup): if I try to set the "Base directory" to something else, it works. This is what I mean specifically: 
![Screenshot_20240622_153713](https://github.com/aurelienpierreeng/ansel/assets/22685799/57f08c61-50ca-4c5b-861f-057c20ae9e10)
This screenshot is taken right after opening Ansel for the first time and *without any files selected* choosing "Copy to disk" (as I've said above this also happens if you first select an image and then select the "Copy to disk"). In this state if I try to choose any type of image Ansel will crash.
Trying running with gdb to get a backtrace yielded nothing.

I've also tested this in a Windows VM with the same conditions and it doesn't crash. It instead tells you "Can't build a valid path" and the import simply fails.

PS: the log is too long to be put in an issue, I've attached a text file with full debug output.
[darktable.txt](https://github.com/user-attachments/files/15937091/darktable.txt)

### Does your problem occur with OpenCL enabled ?

Yes

### Does your problem occur with OpenCL disabled ?

Yes

**Comment by aurelienpierre** [comment]
The bug appears to be that the base folder is not initialized on first run.
