### ISSUE TITLE
Bug: Delete Development

### ISSUE THREAD

**Issue by RyanHarvieStark** [aurelienpierreeng/ansel#351]
### Code of Conduct

- [X] I have read this document and I accept the conditions

### Search previous report

- [X] I have searched my issue

### Computer's operating system

Linux

### What GPU do you have ?

Nvidia

### Ansel version

0.0.0+857~gea7aee827

### Type of binary

Pre-built packages provided by the Ansel project (.AppImage, .EXE)

### What happened?

Delete development has what I think is confusing behaviour. I'm not sure if this can be classed as a bug but it doesn't seem right.

When using delete development, filmic rgb turns on but also color balance rgb is turned on with settings of basic colorfulness standard. Everything else appears to be removed as far as I can see so far.

Shouldn't delete development take the image back to where it was when you had done no edit. In lighttable the image will have no development icon but will still open with filmic rgb and color balance rgb turned on unlike how it would open the first time.

### Does your problem occur with OpenCL enabled ?

I don't know

### Does your problem occur with OpenCL disabled ?

I don't know

**Comment by pedrorrodriguez** [comment]
This can be set in the preferences. By default it enables filmic and color balance RGB to have a basic image that is "closer" to an out of camera jpeg. You can choose something else if that doesn't suit you.

**Comment by Jiyone** [comment]
"Delete development" will remove any edition.
So Ansel will acts like you open the image in darkroom for the first time :
If there are automatic modules presets and if the option that @pedrorrodriguez mentioned above is on "scene-referred", then modules related to those options will be activated.

**Comment by RyanHarvieStark** [comment]
I don't see that option in preferences. I looked because Darktable has that. I understand why you would have filmic with the color balance rgb to adjust color on first opening but it doesn't do that. When I first open an image which has not been edited before those are not enabled. I'm fine with that and I understand why you might want it the other way. The issue is that it's inconsistent because when I delete development those two modules are activated.

**Comment by Jiyone** [comment]
Ah yes sorry, that option has been removed because now there is only one workflow.

**Comment by RyanHarvieStark** [comment]
I removed the images from Ansel then deleted the xmp files. All seems to be fine now. They open with Filmic and Color Balance activated.  I'm not sure what happened but maybe there were xmps in there from Darktable although the images showed no edits.
