### ISSUE TITLE
Bug: export of jpg creates dark images from version 857

### ISSUE THREAD

**Issue by lutz-wbr** [aurelienpierreeng/ansel#356]
### Code of Conduct

- [X] I have read this document and I accept the conditions

### Search previous report

- [X] I have searched my issue

### Computer's operating system

Linux

### What GPU do you have ?

Nvidia

### Ansel version

0.0.0+911~g3fe23ecd6

### Type of binary

Pre-built packages provided by the Ansel project (.AppImage, .EXE)

### What happened?

Hi, unless I missed something:
Exporting images to jpg was absolutely fine up to version 837.
Exported images from version 857 up to and including version 911 are much darker than expected.
The workflow is the same.
Export to *png seems to be affected as well, but i haven't investigated that thoroughly. 

Referring to a  similar report #313 "The export result is ... darker than the central view..." there is neither ToneEQ involved nor any mask applied. Disabling Color balance RGB makes no significant difference.

The zip file attached contains files:
20240716175925_DSC_1212.NEF
20240716175925_DSC_1212.NEF.xmp
version837.jpg
version857.jpg

Let me know if you need further information.
Thank you very much. 
Lutz

[dark_jpgs_837_857.zip](https://github.com/user-attachments/files/16363609/dark_jpgs_837_857.zip)

### Does your problem occur with OpenCL enabled ?

I don't know

### Does your problem occur with OpenCL disabled ?

I don't know

### Previous Ansel version that use to work

Ansel-0.0.0+837.g3799e7893-x86_64.AppImage

**Comment by Tokariew** [comment]
when exporting setting profile to sRGB seems to fix for me

**Comment by lutz-wbr** [comment]
So it does. Thank you very much.
