### ISSUE TITLE
Possible broken color profile?

### ISSUE THREAD

**Issue by vtsisyk** [aurelienpierreeng/ansel#37]
I had noticed that jpeg, i exported from dng in r-darktable has some color artifacts.
Jpg:
![20220910_093436_02](https://user-images.githubusercontent.com/30614987/190623328-17c7ba7c-dae1-4df3-abf6-93d7bc0c9c2f.jpg)
200% to see it more clearly
![20220910_093436_02-edited](https://user-images.githubusercontent.com/30614987/190623405-dd5dd2f9-4c1d-49c9-8f41-67a2e0fd39da.jpg)
Screenshot from phone. Image looks broken
![Screenshot_20220916-174857](https://user-images.githubusercontent.com/30614987/190625473-ae5892a5-be1f-4cf7-a427-3b546defe7f5.png)

I used same xmp-file to repeat this in Darktable 3.8.1, but there is no artifacts:
Jpg:
![20220910_093436_01](https://user-images.githubusercontent.com/30614987/190624304-455f3ad1-86a7-4438-bfe8-d9988ce6b21a.jpg)
200%
![20220910_093436_01-edited](https://user-images.githubusercontent.com/30614987/190624325-913dee19-81f0-480e-97d7-f065034ef6ff.jpg)
Screenshot from phone. 
![Screenshot_20220916-174902](https://user-images.githubusercontent.com/30614987/190624452-166331c2-6106-4a2d-920a-ae90a01dbdd7.png)

I haven't tried testing it on upstream darktable though. 
I use up to date  r-darktable 3.9.0+1730~g16aa4bf6b-dirty on Fedora 36 x86_64

[broken_image.tar.gz](https://github.com/Aurelien-Pierre/R-Darktable/files/9583474/broken_image.tar.gz)

**Comment by aurelienpierre** [comment]
It's probably not a color profile issue because it only happens in black regions, so this has something to do with clipping or rounding. I will have a look.

**Comment by pedrorrodriguez** [comment]
Does the issue persist in recent versions of Ansel? What about upstream darktable?

**Comment by aurelienpierre** [comment]
I don't reproduce on current master with the provided DNG and XMP. Re-open if problem persists, but I will need more details on GPU etc.
