### ISSUE TITLE
Bug: color pipet not showing values

### ISSUE THREAD

**Issue by Kape60** [aurelienpierreeng/ansel#386]
### Code of Conduct

- [X] I have read this document and I accept the conditions

### Search previous report

- [X] I have searched my issue

### Computer's operating system

Windows 7, 8, 10, or 11

### What GPU do you have ?

AMD/ATI

### Ansel version

0.0.0-922~g7f23d9d38

### Type of binary

Pre-built packages provided by the Ansel project (.AppImage, .EXE)

### What happened?

The color pipet in the left panel doesn't show any other values than 0-0-0 when used alone. On the other hand, when a pipet is activated in an other module (for instance color calibration) measured values are shown in the left panel. 

### Does your problem occur with OpenCL enabled ?

Yes

### Does your problem occur with OpenCL disabled ?
Yes

### Previous Ansel version that use to work

Not used previous versions

**Comment by lukadh** [comment]
Hey Kape60,

the color picker is broken for some time now and I was a little bit bugged that Aurélien didn't seem to care too much. Anyway some weeks ago someone shared the following podcast in the Ansel Matrix chat: (COLOR MENTOR PODCAST Episode 5 Troy Sobotka interview - Part 1)[https://www.youtube.com/watch?v=TORPnxQeo7g] 

Of course that doesn't fix the tool, but for me it really made me miss it less :D Especially the optical "illusions" in the  first bit of the video are very fascinating and worth knowing about. The whole thing is nearly 5 hours long - just so you are warned.

**Comment by Kape60** [comment]
Bonjour lukadh,

Thanks for the advise. I am going to look at that. I know human visual perceptin doesn't overlap with technical measurements, and therefore photograph PT is not just about manipulating figures. At some point we have to train our eyes including  some knowledge about "visual illusions".
