### ISSUE TITLE
R&Darktable to support CR3 raws from Canon EOS R7

### ISSUE THREAD

**Issue by MaTeng211** [aurelienpierreeng/ansel#40]
Unlike with the most recent "stable" version of darktable 4.0.1 , I can't get CR3 raw files coming from the EOS R7 to work with the master branch of R&Darktable.

Building the version works fine for me, but unlike Raws from R5 and R6, which seem to work, CR3 raws from R7 are nit working with the recent master.

**Comment by MaTeng211** [comment]
Comparing the src-tree for darktable v4.0.1 and R&Darktable master, I assume, that the issue relatges to the version of 
LibRaw used: 
R&Darktable master uses <LibRaw snapshot 20211> as seen in src/external, while dartable v4.0.1 incoporates <LibRaw 0.21-Beta1> 
And with this version, there comes the support for the EOS R7 CR3 . So clear to me now why the current master for R&Darktable does not support my the raw files for the EOS R7.

**Comment by aurelienpierre** [comment]
See https://github.com/Aurelien-Pierre/Ansel/pull/41

**Comment by MaTeng211** [comment]
I guess this is closed with new version of libraw now merged per #41
