### ISSUE TITLE
color profiles

### ISSUE THREAD

**Issue by aadm** [aurelienpierreeng/ansel#49]
Whenever I open an image in darkroom I have this warning message:

```
(base) aadm@psion:~ $ ansel
[get_output_profile] called with ICC type -1
[colorspaces] Trying to fetch embedded profile.
image 56154
embedded color profile NOT found
embedded matrix NOT found
[colorspaces] could not fetch the profile.
[colorspaces] WARNING: no colorspace found, sRGB will be tagged in final exported file. Colors may be inconsistent
```

I'm simply not sure about all these warnings. Is there a problem? Why does it say "no colorspace found"? These are all raw files. The fact that the output will be tagged sRGB is not a problem (I think) because that's the default you want to send out to a printing service for example. 

* version : this is ansel c5a7bb6
* OS : e.g. Linux - Ubuntu 22.04.01 LTS, Gnome version 42.5, X11 Windowing system
* Memory :  32 Gb
* Graphics card :  Nvidia GeForce RTX 2070 Mobile
* Graphics driver :  latest?
* OpenCL installed  & activated: yes

## extra information

I also have issues with my display profile as I also get an error from ansel-cmstest:

```
(base) aadm@psion:~ $ /opt/ansel/bin/ansel-cmstest 
ansel-cmstest version c5a7bb6
this executable was built with colord support enabled
ansel itself was built with colord support enabled

primary CRTC is at CRTC 0
CRTC for screen 0 CRTC 1 has no mode or no output, skipping
CRTC for screen 0 CRTC 2 has no mode or no output, skipping
CRTC for screen 0 CRTC 3 has no mode or no output, skipping
CRTC for screen 0 CRTC 4 has no mode or no output, skipping
CRTC for screen 0 CRTC 5 has no mode or no output, skipping
CRTC for screen 0 CRTC 6 has no mode or no output, skipping

DP-0	the X atom and colord returned different profiles
	X atom:	_ICC_PROFILE (724 bytes)
		description: sRGB built-in
	colord:	"/home/aadm/.local/share/icc/SW2700 #1 2022-12-15 10-00 120cdm² D6500 2.2 F-S XYZLUT+MTX.icc"
		description: SW2700 #1 2022-12-15 10-00 120cdm2 D6500 2.2 F-S XYZLUT+MTX

Better check your system setup
 - some monitors reported different profiles
You may experience inconsistent color rendition between color managed applications
```

The profile for my monitor was made with DisplayCAL which then proceeds to install it; it seems like colord sees it but then I have this warning message about X atom and colord diverging. I don't know what is X atom and how would I "change" it to load the correct profile. This has probably nothing to do with the above issue though but I thought better to mention it.

**Comment by aurelienpierre** [comment]
Don't worry, it's debug info. It's normal that embedded profiles are not found for raw files, they have none.

**Comment by aadm** [comment]
thanks @aurelienpierre !
