### ISSUE TITLE
Graphic is not reset when color EQ module is reset

### ISSUE THREAD

**Issue by RawConvert** [aurelienpierreeng/ansel#5]
ubuntu 20.04    R&Dt  3.9.0+1647~gebb12ab06      color EQ branch   
i7  NO GPU

To reproduce - increase a slider for saturation or brightness, see the graphic change, click reset, slider resets, graphic doesn't.

![Screenshot from 2022-06-23 17-46-43](https://user-images.githubusercontent.com/16868433/175352706-67e53ff9-8eec-4a22-a3c4-c5304506ff61.png)
.

**Comment by RawConvert** [comment]
Gutted to see this is no.5 rather than no.1

**Comment by aurelienpierre** [comment]
> Gutted to see this is no.5 rather than no.1

LOL.

Color EQ is still heavily experimental, I would like feedback only on the color/pixel behaviour for now. GUI stuff is cosmetic and can be fixed anytime.
