### ISSUE TITLE
Decrease the value range of chroma sliders in the 4-ways tab of the Color balance RGB module

### ISSUE THREAD

**Issue by pedrorrodriguez** [aurelienpierreeng/ansel#51]
**Issue**

According to the recent poll I ran (https://github.com/aurelienpierreeng/ansel/discussions/46), the value range of the chroma sliders in the 4-ways tab is too large, making it difficult for users to quickly and precisely pick their desired value. 

Over 80% of participants in the survey don't use the top quarter in any of the four sliders on a regular basis. Moreover, only 15% of participants use the shadows lift chroma slider between its middle and maximum value. 

<img src="https://user-images.githubusercontent.com/64545422/208933483-e4818dcd-aa58-4908-a10a-2ac8799ebd80.jpg" width=50% height=50%>
<img src="https://user-images.githubusercontent.com/64545422/208933499-500573e8-cf28-46f7-9d60-fdad3f64f1e3.jpg" width=50% height=50%>
<img src="https://user-images.githubusercontent.com/64545422/208933503-7ec50563-3127-4ef8-8625-254bac6b95f4.jpg" width=50% height=50%>
<img src="https://user-images.githubusercontent.com/64545422/208933518-d10304d5-f40f-4ad1-ae93-07290a9c0eef.jpg" width=50% height=50%>
<img src="https://user-images.githubusercontent.com/64545422/208933526-d9d0baba-68d4-429f-a0b0-a2d2b7d79654.jpg" width=50% height=50%>

**Expected behavior**

Users are able to pick values quickly and effortlessly. I suggest a 25% decrease of the current value range for each slider, potentially more for the shadows lift chroma.

**Comment by aurelienpierre** [comment]
Fixed by #83 I believe.
