### ISSUE TITLE
Missing fields in Open & Import

### ISSUE THREAD

**Issue by hgmarty** [aurelienpierreeng/ansel#53]
Hello,

in module Import from camera, there is some missing fields in English as you can see in the screenshot :
![Capture d’écran de 2022-12-28 18-17-43](https://user-images.githubusercontent.com/67023978/209849409-1f48073c-9354-438c-93a1-d23150f5d00b.png)

In a specific language like French, the fileds are the same like this :
![Capture d’écran de 2022-12-28 18-18-48](https://user-images.githubusercontent.com/67023978/209850128-9857ba77-1ba1-4c20-ae5e-0a6f71968cb8.png)  
I have seen the same in spanish but with a different name in fields

I continue the review
Thank you

**Comment by aurelienpierre** [comment]
Seems to work now, does it ?

**Comment by hgmarty** [comment]
Fix with #5ae8b7705557228206d50e48ca728289ab8b67bd
