### ISSUE TITLE
Packaging Ansel for Snapstore

### ISSUE THREAD

**Issue by arky** [aurelienpierreeng/ansel#62]
**What is the current problem you are facing ?**
It would be good if Ansel development and stable release could released in the snapstore. This would enable users to quickly install the packages to test the unstable and stable version on their Ubuntu systems. 

**Additional context**
Darktable has already been packaged as snap. This bug only relates to setting up and publishing ansel packages to the store. 
https://snapcraft.io/darktable

**Comment by aurelienpierre** [comment]
Nope. Snap sucks. There is an AppImage, the rest is not my problem.
