### ISSUE TITLE
Failed to load module "canberra-gtk-module"

### ISSUE THREAD

**Issue by lartaud** [aurelienpierreeng/ansel#71]
**Describe the bug/issue**
I get the following message each time I start Ansel-0.0.0+53~g664c527d3-x86_64.AppImage:
`Gtk-Message: 17:18:35.117: Failed to load module  "canberra-gtk-module"`

**To Reproduce**
Just run the AppImage

**Platform**
* Ansel version : Ansel-0.0.0+27~gd09679b3f-x86_64.AppImage
* OS                : 6.1.3-arch1-1
* Linux - Distro    : Arch Linux
* Memory            : 32GB
* Graphics card     : NVIDIA GeForce GTX 1060 6GB
* Graphics driver   : official nvidia drivers 525.78.01
* OpenCL installed  : opencl-nvidia 525.78.01
* OpenCL activated  : yes
* Xorg              : 21.1.6
* Desktop           : AwesomeWM
* GTK+              : 3.24.36

**Additional context**
 - I did not get this message when running darktable 4.0.1, nor do I get it with darktable 4.2.0 (can’t test with 4.0.1 any more because of an updated dependency preventing it from starting)

**Comment by lartaud** [comment]
Oops…
Of course, the Ansel version is:
Ansel-0.0.0+53~g664c527d3-x86_64.AppImage

**Comment by aurelienpierre** [comment]
You can try installing `libcanberra` from your software manager. It's weird because I don't know of a part of the software using Canberra, maybe it's a dependency of the Gtk3 stack. Internet tells me Canberra is used to trigger sound events like notifications and (thank God) we don't do that.

**Comment by aurelienpierre** [comment]
Right, I found that : https://bugs.archlinux.org/task/73517

I think you can safely ignore this warning.
