### ISSUE TITLE
I got Ansel built for MacOS but with some (minor) issues.

### ISSUE THREAD

**Issue by lologor** [aurelienpierreeng/ansel#73]
**Describe the bug/issue**
I first build Darktable 4.2 following the instructions written in packaging/macos/BUILD.txt. After installing all dependencies I could compile and install. DT 4.2 is running up.

Following the same instruction I could build Ansel. Compiler ran into one issue by compiling src/osx/osx.mm. Replacing through the one of DT 4.2 did the trick. Then I ran in two issues during install (using "cmake --install ."): Install wanted to install the executable "darktable-curve-tool-helper" but "ansel-curve-tool-helper" has been created. The same happened with "darktable-gen-noiseprofile" ("ansel-gen-noiseprofile" has been created). After manually renaming the executable file names in the cmake install scripts, all ran through.

Ansel is now running: Few pictures loaded and "developped" with standard settings: No issue so far.

**To Reproduce**
- Follow instruction of (DT 4.2) packaging/macos/BUILD.txt by installing dependencies
- git clone ansel
- run cmake to create configurations
- run make
- compiler stops by compiling src/macos/osx.mm
- run cmake --install .
- cmake stops by installing darktable-curve-tool-helper and darktable-gen-noiseprofile

**Expected behavior**
- Compile runs through without error
- Install runs without error

**Platform**

* ansel version : master (8/1/2023)
* OS                : MacOS Monterey 12.6.2 Intel
* Linux - Distro    : 
* Memory            :  24GB
* Graphics card     :  Radeon RX 580 8 GB
* Graphics driver   :  Native
* OpenCL installed  :  yes
* OpenCL activated  :  yes
* Xorg              :  n/a
* Desktop           :  n/a
* GTK+              :  macports 3.24.34
* gcc               :  Apple clang version 14.0.0
* cflags            :  
* CMAKE_BUILD_TYPE  :  cmake .. -DCMAKE_OSX_DEPLOYMENT_TARGET=10.14 -DOpenMP_C_INCLUDE_DIR=/opt/local/include/libomp -DOpenMP_CXX_INCLUDE_DIR=/opt/local/include/libomp -DCMAKE_LIBRARY_PATH=/opt/local/lib/libomp -DBINARY_PACKAGE_BUILD=ON -DRAWSPEED_ENABLE_LTO=ON -DBUILD_CURVE_TOOLS=ON -DBUILD_NOISE_TOOLS=ON -DDONT_USE_INTERNAL_LUA=OFF

**Comment by AlynxZhou** [comment]
I can reproduce this, too. It looks that some rename is missing in CMake and I may try to solve it tomorrow.

**Comment by AlynxZhou** [comment]
Maybe <https://github.com/aurelienpierreeng/ansel/pull/76> fixes it for you or may not, it do works on my system (not a macOS, though).
