### ISSUE TITLE
Clicking Display Metadata enlarges window in vertical and make it unable to shrink in vertical

### ISSUE THREAD

**Issue by AlynxZhou** [aurelienpierreeng/ansel#78]
**Describe the bug/issue**

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Open ansel
2. Click on Display Metadata on the right side

**Expected behavior**

Window do not expand, all things in screen

**Actually happened**

Window becomes larger even in maximize state, thumbnails bar is out of screen, and cannot shrink window in vertical if it's not maximized.

**Screencast**

[Screencast from 2023-01-19 09-49-39.webm](https://user-images.githubusercontent.com/8444615/213336828-1c153177-faa9-4f65-a44f-052ab05067d7.webm)

**Which commit introduced the error**

Not sure

_A bisect is much appreciated and can significantly simplify the developer's job._
_HowTo: https://github.com/darktable-org/darktable/wiki#finding-bug-causes and https://www.youtube.com/watch?v=D7JJnLFOn4A_

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : this is ansel 459c476f3
* OS                : 6.1.4-arch1-1
* Linux - Distro    : Arch Linux
* Memory            : 32G
* Graphics card     : NVIDIA RTX 2070 Super
* Graphics driver   : nvidia
* OpenCL installed  : y
* OpenCL activated  : y
* Xorg              : Wayland
* Desktop           : GNOME
* GTK+              : 3.24.36
* gcc               : 12.2.0
* cflags            : 
* CMAKE_BUILD_TYPE  : Release

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **not sure**
 - Can you reproduce with a RAW or Jpeg or both? **both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**
 - Do you use lua scripts? NO

**Comment by AlynxZhou** [comment]
I forget to record pointer in the first video:

[Screencast from 2023-01-19 09-54-55.webm](https://user-images.githubusercontent.com/8444615/213337320-a962e4e6-58f4-482d-81bf-e201c899c93f.webm)

**Comment by aurelienpierre** [comment]
Ctrl + Scroll down on the window to reduce its size. I'm sorry, it's yet-another-darktable-UX-innovation.

**Comment by AlynxZhou** [comment]
I cannot reproduce it now, don't know why but let's close this.
