### ISSUE TITLE
The button for collapsing groups seems to have disappeared

### ISSUE THREAD

**Issue by koslowj** [aurelienpierreeng/ansel#79]
In version 5db60ce (just compiled) the button to collapse groups in the lighttable (first icon, upper right)
seems to have disappeared.  Double clicking on the group leader doesn't collapse the group either.
The previous version was compiled two days ago.

Ansel compiled under Gentoo Linux 5.15.88 with gcc 11.3.1_p20221209 and glibc 2.36-r5; lua 5.1.5-r200

 ---------------------------------------------------------------

**Comment by aurelienpierre** [comment]
Look at the bottom toolbar.

**Comment by koslowj** [comment]
OK, thanks! Must be the late hour...

-- If I don't see you no more on this world
Juergen Koslowski I'll meet you on the next one
***@***.******@***.***) and don't be late!Sent from Swiss-based encrypted [ProtonMail](https://protonmail.com), Jimi Hendrix (Voodoo Child, SR)

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
