### ISSUE TITLE
Module order in "Apply development - Selective copy" different to darkroom

### ISSUE THREAD

**Issue by l-28** [aurelienpierreeng/ansel#82]
**What is the current problem you are facing ?**
When copying selective modules from one photo to another I think it is unintuitive to go through a list of modules in a different order in the pop-up window compared to the order in which they appear in the right panel of the darkroom.

**Where in your workflow does your problem occur ?**
Especially when copying modules in darkroom view using keyboard shortcuts I am still in the hang of the module order of the right panel. 

**Additional context**
As a relatively new Ansel user I still struggle to navigate through the processing modules. That pop-up window takes away all the good feeling of "knowing where to look for what". At the same time I realise it's just a list, that I can read top to bottom every time.

**Comment by aurelienpierre** [comment]
Pipeline is broken since 2019 regarding the order of copy when using multiple instances and/or non-default pipeline order.

**Comment by aurelienpierre** [comment]
This is connected only to the GUI  being ordered differently ?
