### ISSUE TITLE
Single click pictures in the bottom picture row cannot switch picture in darkroom, but double click works.

### ISSUE THREAD

**Issue by AlynxZhou** [aurelienpierreeng/ansel#89]
**Describe the bug/issue**

When I want to change picture with the bottom picture row in darkroom, I have to use double click, single click does not work.

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to Darkroom
2. Click on another picture in the bottom row.

**Expected behavior**

switch picture

**What happened**

Not changed, if you open "display metadata", you'll see single click updated metadata, but not change picture. Double click works, is the by design or a bug?

**Screenshots**
_(if applicable)_

**Screencast**
_(if applicable)_

**Which commit introduced the error**
_If possible, please try using `git bisect` to determine which commit introduced the issue and place the result here._

_A bisect is much appreciated and can significantly simplify the developer's job._
_HowTo: https://github.com/darktable-org/darktable/wiki#finding-bug-causes and https://www.youtube.com/watch?v=D7JJnLFOn4A_

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : git master
* OS                : Linux 6.1.8
* Linux - Distro    : Arch Linux
* Memory            : 32G
* Graphics card     : NVIDIA RTX2070Super
* Graphics driver   : nvidia
* OpenCL installed  : yes
* OpenCL activated  : yes
* Xorg              : Wayland
* Desktop           : GNOME
* GTK+              : 3.24.36
* gcc               : 12.2.1
* cflags            : 
* CMAKE_BUILD_TYPE  : Release

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **not sure**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**
 - Do you use lua scripts?
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by l-28** [comment]
Hey @AlynxZhou,

that is intended behaviour. It was changed to have consistent behaviour between lighttable and filmstrip. I don't know how to properly reference a commit, so here is the URL 😅  https://github.com/aurelienpierreeng/ansel/commit/70a0b4f7c09493dc95b20d27b8c0dcd94cf07d00

**Comment by AlynxZhou** [comment]
If so, is it a bug that single click updates display metadata?

**Comment by l-28** [comment]
Are you sure, that it is the click that updates the display metadata? When I checked the display metadata changes to the image that I'm hovering with my mouse, but shows the metadata of the opened image once I move the pointer away from filmstrip - no matter which image I selected by single clicking. 

That seems in line with: https://ansel.photos/en/doc/special-topics/from-darktable/#behaviours 

With the limitations of the fact that the opened imaged is always selected: https://github.com/aurelienpierreeng/ansel/issues/75#issuecomment-1399035079

**Comment by AlynxZhou** [comment]
> Are you sure, that it is the click that updates the display metadata? When I checked the display metadata changes to the image that I'm hovering with my mouse, but shows the metadata of the opened image once I move the pointer away from filmstrip - no matter which image I selected by single clicking.
> 

You are right, I checked again and it is the same as you described, quite a useful feature and thank you for your reply!

> That seems in line with the "mouse over" events described here: https://ansel.photos/en/doc/special-topics/from-darktable/#behaviours
> 
> With the limitations of the fact that the opened imaged is always selected: [#75 (comment)](https://github.com/aurelienpierreeng/ansel/issues/75#issuecomment-1399035079) (last 3 comments)

**Comment by AlynxZhou** [comment]
> That seems in line with the "mouse over" events described here: https://ansel.photos/en/doc/special-topics/from-darktable/#behaviours

And also, this page is really helpful, I don't find it by myself, thank you again!
