### ISSUE TITLE
recent collections open with single click

### ISSUE THREAD

**Issue by lukadh** [aurelienpierreeng/ansel#93]
**Describe the bug/issue**
Items in the "Recent collections" module open with a single click while items in "Collect" are opened by double clicking. Double clicking in the "Recent collections" module results in two consecutive actions: showing the intended collection and then showing the (random) collection that gets moved under the curser. 

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to 'Recent collections'
2. Open 'any collection but the first'
3. Check the shown collection
4. Realise it's another collection from the list

**Expected behavior**
Show the collection opened in step 2

* Ansel version : 0.0.0+120~gd9e1b5a

**Comment by aurelienpierre** [comment]
To do:

in `src/libs/collect.c`, remove the `click` event and remap the click callback to a `button-pushed` event and handle both GDK clic and double-clic.

**Comment by pedrorrodriguez** [comment]
Fixed by https://github.com/aurelienpierreeng/ansel/commit/fc048140a90a2ee4bab35c13439562f782a0dd28
