### ISSUE TITLE
Obscure Parameters drop-down in "Open & Import" module

### ISSUE THREAD

**Issue by lukadh** [aurelienpierreeng/ansel#94]
**What is the current problem you are facing ?**
The secondary drop-down "Parameters" in the "Open & Import" module hides the "initial star rating" setting in an unfamiliar place (to new users). https://github.com/aurelienpierreeng/ansel/issues/88
In addition it introduces issues with checkboxes, because the secondary drop-down has a different background-color than the rest of the dialoges (with checkboxes). https://github.com/aurelienpierreeng/ansel/issues/92

**Additional context**
- In other modules like "Color calibration" or "Exposure" the secondary drop-down can be ignored unless the user wants a very specific function.
- I didn't find any checkboxes in secondary drop-downs of other modules (though one could look more thoroughly)
- The "Export" module which I would think of beeing very related to the "Open & Import" module handles a lot more parameters on a single level.

**May I suggest...**
Instead of making a special styling-case for "checkboxes in secondary drop-downs" and keep pointing out the existance of the "Parameters" drop-down, I think matching the layout of the "Import" module with the "Export" module would be a valid approach.
<img src="https://user-images.githubusercontent.com/64734384/218246748-4c62aa42-70f9-4701-aeb5-a1bff485dea7.png" alt="export" width="45%"> <img src="https://user-images.githubusercontent.com/64734384/218246749-42e43017-28ff-4bc4-ad82-e729615cf406.png" alt="import" width="45%">

**Comment by aurelienpierre** [comment]
Mid-term plan is to get a `File` header menu with `Import` and `Export` menus, so both modules will be moved to their own pop-up.

Like in most other software.

**Comment by pedrorrodriguez** [comment]
Quick question. Since the tethering view is gone.. Does the import from camera option still make sense?

**Comment by aurelienpierre** [comment]
Import from camera is the "copy on disk then add to library" option. It doesn't rely on GPhoto or tethering.

**Comment by pedrorrodriguez** [comment]
> Mid-term plan is to get a `File` header menu with `Import` and `Export` menus, so both modules will be moved to their own pop-up.
> 
> Like in most other software.

If this is already on your todo, should I close this issue?

**Comment by aurelienpierre** [comment]
Closing happens when merging the code

**Comment by pedrorrodriguez** [comment]
I know. Only that the issue was already going to be fixed by moving both modules to the global menu, and the proposed solution is not the one you will end up going for. If you'd like me to leave it open that's fine, but I was just trying to remove as much clutter from your inbox as possible

**Comment by aurelienpierre** [comment]
Rewritten
