### ISSUE TITLE
Crashes on Windows 10

### ISSUE THREAD

**Issue by OK-One** [aurelienpierreeng/ansel#98]
Thought it good to drop the log files, from some crashes I experienced. I'm running on an Intel 7th gen i5 mobile processor with 16GB RAM.

Pierre best wishes, and thank you for providing an excellent tool.

[ansel_bt_MORG01.txt](https://github.com/aurelienpierreeng/ansel/files/10770632/ansel_bt_MORG01.txt)
[ansel_bt_WQVG01.txt](https://github.com/aurelienpierreeng/ansel/files/10770633/ansel_bt_WQVG01.txt)
[ansel_bt_XQVG01.txt](https://github.com/aurelienpierreeng/ansel/files/10770634/ansel_bt_XQVG01.txt)
[ansel_bt_AAXG01.txt](https://github.com/aurelienpierreeng/ansel/files/10770635/ansel_bt_AAXG01.txt)

**Comment by AlynxZhou** [comment]
It seems that only <https://github.com/aurelienpierreeng/ansel/files/10770633/ansel_bt_WQVG01.txt> contains a valid trace and others give no output (not sure why), I am not familiar with how modules work, but hoping this could save less time to debug for other devs.

**Comment by OK-One** [comment]
Huge thank you to everyone working on the Ansel code. I appreciate all of you. Thank you. The ethos of Ansel makes sense to me. Less bloat. More focus on the essentials. And over time better performance. I like it. Less is more...

**Comment by aurelienpierre** [comment]
Looks related to memory cache size or possibly tiling size.

**Comment by OK-One** [comment]
My Ansel version is - 0.0.0+53~g664c527d3

I was most likely In Darkroom, either:

1. Moving to edit another image, or duplicate, by single clicking on the row of images at the bottom, 

or 

2. Double clicking to edit a duplicate in the (Duplicate Manager), on the left of the screen.

It could be related to the way I have been running my Windows 10, disabling the paging (swap aka virtual) memory, so it only uses only actual RAM predominantly. So it could be that I had ran out of actual RAM, and it was unable to allocate memory to Ansel.

I have just enabled a 10GB paging on my laptop with 16GB or physical real RAM, so hopefully this should solve the problem. We'll see. !

**Comment by pedrorrodriguez** [comment]
> My Ansel version is - 0.0.0+53~g664c527d3
> 
> I was most likely In Darkroom, either:
> 
> 1. Moving to edit another image, or duplicate, by single clicking on the row of images at the bottom,
> 
> or
> 
> 2. Double clicking to edit a duplicate in the (Duplicate Manager), on the left of the screen.
> 
> It could be related to the way I have been running my Windows 10, disabling the paging (swap aka virtual) memory, so it only uses only actual RAM predominantly. So it could be that I had ran out of actual RAM, and it was unable to allocate memory to Ansel.
> 
> I have just enabled a 10GB paging on my laptop with 16GB or physical real RAM, so hopefully this should solve the problem. We'll see. !

Did it fix the issue?
